import type { Comic1PackageContent } from './types';
import qrCandiJawi from '@/features/comics/comic-1/assets/qr/candi-jawi.png';
import qrKubus from '@/features/comics/comic-1/assets/qr/kubus.png';
import qrBalok from '@/features/comics/comic-1/assets/qr/balok.png';
import qrPrisma from '@/features/comics/comic-1/assets/qr/prisma-segi-empat.png';
import qrLimas from '@/features/comics/comic-1/assets/qr/limas-segi-empat.png';
import qrKerucut from '@/features/comics/comic-1/assets/qr/kerucut.png';

import coverImg from '@/features/comics/comic-1/assets/cover/cover.png';

import { AtapImg as appAtap, OrnamentImg as appOrnament, TanggaImg as appTangga } from '@/features/comics/comic-1/assets/application';

import identKubus from '@/features/comics/comic-1/assets/identification/Kubus.png';
import identBalok from '@/features/comics/comic-1/assets/identification/Balok.png';
import identPrisma from '@/features/comics/comic-1/assets/identification/Prismasegiempat.png';
import identLimas from '@/features/comics/comic-1/assets/identification/Limassegiempat.png';
import appKubus from '@/features/comics/comic-1/assets/identification/Kubus.png';
import appBalok from '@/features/comics/comic-1/assets/identification/Balok.png';
import appPrisma from '@/features/comics/comic-1/assets/identification/Prismasegiempat.png';
import appLimas from '@/features/comics/comic-1/assets/identification/Limassegiempat.png';
import appKerucut from '@/features/comics/comic-1/assets/identification/Kerucut.png';

import { KubusImg as argKubus, BalokImg as argBalok, PrismaImg as argPrisma, LimasImg as argLimas, KerucutImg as argKerucut } from '@/features/comics/comic-1/assets/argument';

import navKubus from '@/features/comics/comic-1/assets/navigation/kubus.svg';
import navBalok from '@/features/comics/comic-1/assets/navigation/balok.svg';
import navPrismaPreview from '@/features/comics/comic-1/assets/navigation/prisma-preview.svg';
import navKerucut from '@/features/comics/comic-1/assets/navigation/kerucut.svg';
import navDefault from '@/features/comics/comic-1/assets/navigation/default.svg';

export const packageContent: Comic1PackageContent = {
  metadata: {
    comicId: 1,
    title: 'Petualangan Bangun Ruang Candi Jawi',
    subtitle: 'Etnomatematika Bangun Ruang',
    location: 'Candi Jawi, Pasuruan',
    classLevel: 'VI',
    cover: coverImg.src,
    thumbnail: coverImg.src,
    learningTargets: [
      'Mengidentifikasi bangun ruang yang muncul pada Candi Jawi',
      'Menghubungkan bentuk arsitektur candi dengan bangun ruang',
      'Menjelaskan alasan dan ciri bangun ruang menggunakan bahasa sederhana',
    ],
    synopsis: 'Komik ini memperkenalkan bangun ruang yang dapat diamati pada bagian-bagian arsitektur Candi Jawi.',
  },
  learningObjects: [
    {
      id: 'komik1-kubus',
      title: 'Kubus',
      description: 'Bangun ruang yang menyerupai bagian utama bangunan yang tampak kuat dan beraturan.',
      page: 1,
      qrImage: qrKubus.src,
      navImage: navKubus.src,
      objectImage: appKubus.src,
      modelUrl: 'https://app-edu.assemblrworld.com/en/creation/-eGQgkYkAKlbGegmVGej',
      embedUrl: 'https://app-edu.assemblrworld.com/en/creation/-eGQgkYkAKlbGegmVGej',
      viewerType: 'url',
      provider: 'Assemblr',
      aiPrompt: 'Jelaskan ciri kubus, sisi, rusuk, dan titik sudut yang terlihat pada objek ini.',
      question: 'Apa ciri khas kubus yang terlihat pada objek ini?',
      answer: 'Kubus memiliki 6 sisi persegi, 12 rusuk, dan 8 titik sudut.',
      feedback: 'Benar, kubus bisa dikenali dari sisi-sisinya yang sama besar dan bentuk persegi.',
    },
    {
      id: 'komik1-balok',
      title: 'Balok',
      description: 'Bangun ruang yang terlihat pada bagian struktur yang memanjang dan kokoh.',
      page: 2,
      qrImage: qrBalok.src,
      navImage: navBalok.src,
      objectImage: appBalok.src,
      modelUrl: 'https://app-edu.assemblrworld.com/en/creation/-hwhAtiZhyCivpQ2Jl5Z',
      embedUrl: 'https://app-edu.assemblrworld.com/en/creation/-hwhAtiZhyCivpQ2Jl5Z',
      viewerType: 'url',
      provider: 'Assemblr',
      aiPrompt: 'Jelaskan perbedaan balok dengan kubus berdasarkan panjang, lebar, dan tinggi.',
      question: 'Bagaimana cara membedakan balok dengan kubus?',
      answer: 'Balok memiliki sisi-sisi berbentuk persegi panjang, sedangkan kubus semua sisinya sama.',
      feedback: 'Bagus, balok dapat dikenali dari sisi-sisi yang tidak semuanya sama panjang.',
    },
    {
      id: 'komik1-prisma',
      title: 'Prisma Segi Empat',
      description: 'Bangun ruang yang terlihat pada bagian ornamen dan sisi tegak yang tersusun berlapis.',
      page: 3,
      qrImage: qrPrisma.src,
      navImage: navPrismaPreview.src,
      objectImage: appPrisma.src,
      modelUrl: 'https://app-edu.assemblrworld.com/en/creation/-PdcSjQ4sYkREdgHK3rX',
      embedUrl: 'https://app-edu.assemblrworld.com/en/creation/-PdcSjQ4sYkREdgHK3rX',
      viewerType: 'url',
      provider: 'Assemblr',
      aiPrompt: 'Jelaskan alas, tutup, dan sisi tegak prisma segi empat.',
      question: 'Apa saja bagian utama prisma segi empat?',
      answer: 'Prisma segi empat memiliki dua alas yang sejajar dan sisi tegak berbentuk persegi panjang.',
      feedback: 'Benar, prisma segi empat mudah dikenali dari dua alas dan sisi tegak yang membentuk bidang.',
    },
    {
      id: 'komik1-limas',
      title: 'Limas Segi Empat',
      description: 'Bangun ruang yang sesuai untuk bagian puncak yang menonjol dan meruncing.',
      page: 4,
      qrImage: qrLimas.src,
      navImage: navDefault.src,
      objectImage: appLimas.src,
      modelUrl: 'https://app-edu.assemblrworld.com/en/creation/-499KAWhzbvlKt5wECkt',
      embedUrl: 'https://app-edu.assemblrworld.com/en/creation/-499KAWhzbvlKt5wECkt',
      viewerType: 'url',
      provider: 'Assemblr',
      aiPrompt: 'Jelaskan bentuk alas dan sisi tegak limas segi empat.',
      question: 'Mengapa limas segi empat punya puncak tajam?',
      answer: 'Karena semua sisi tegak bertemu di satu titik puncak.',
      feedback: 'Betul, limas segi empat memiliki satu puncak dan alas berbentuk segi empat.',
    },
    {
      id: 'komik1-kerucut',
      title: 'Kerucut',
      description: 'Bangun ruang yang menyerupai bagian puncak yang membentuk titik tajam.',
      page: 5,
      qrImage: qrKerucut.src,
      navImage: navKerucut.src,
      objectImage: appKerucut.src,
      modelUrl: 'https://app-edu.assemblrworld.com/en/creation/-HE74wRR8CK9nJFAybzt',
      embedUrl: 'https://app-edu.assemblrworld.com/en/creation/-HE74wRR8CK9nJFAybzt',
      viewerType: 'url',
      provider: 'Assemblr',
      aiPrompt: 'Jelaskan ciri kerucut dan hubungan antara alas, tinggi, dan sisi miring.',
      question: 'Apa ciri utama kerucut?',
      answer: 'Kerucut memiliki alas lingkaran dan satu titik puncak.',
      feedback: 'Ya, kerucut bisa dikenali dari alas bundar dan bentuk yang meruncing ke atas.',
    },
  ],
  qrCode: [
    { id: 'komik1-qr-candi-jawi', imageSrc: qrCandiJawi.src, alt: 'QR Candi Jawi', label: 'Candi Jawi', description: 'Pindai QR ini untuk melihat model 3D Candi Jawi.' },
    { id: 'komik1-qr-1', imageSrc: qrKubus.src, alt: 'QR Kubus', label: 'Kubus', description: 'Pindai QR ini untuk melihat model 3D kubus terkait bagian Candi Jawi.' },
    { id: 'komik1-qr-2', imageSrc: qrBalok.src, alt: 'QR Balok', label: 'Balok', description: 'Pindai QR ini untuk melihat model 3D balok terkait bagian Candi Jawi.' },
    { id: 'komik1-qr-3', imageSrc: qrPrisma.src, alt: 'QR Prisma', label: 'Prisma Segi Empat', description: 'Pindai QR ini untuk melihat model 3D prisma segi empat terkait bagian Candi Jawi.' },
    { id: 'komik1-qr-4', imageSrc: qrLimas.src, alt: 'QR Limas', label: 'Limas Segi Empat', description: 'Pindai QR ini untuk melihat model 3D limas segi empat terkait bagian Candi Jawi.' },
    { id: 'komik1-qr-5', imageSrc: qrKerucut.src, alt: 'QR Kerucut', label: 'Kerucut', description: 'Pindai QR ini untuk melihat model 3D kerucut terkait bagian Candi Jawi.' },
  ],
  model3D: [
    { id: 'komik1-model-candi-jawi', title: 'Candi Jawi', arUrl: 'https://skfb.ly/6tTpq', embedUrl: 'https://sketchfab.com/models/83da3450467747fda7872c5a9392ffac/embed', viewerType: 'embed', page: 0, description: 'Model 3D lengkap Candi Jawi yang sesuai dengan QR Candi Jawi.', provider: 'Sketchfab' },
    { id: 'komik1-model-1', title: 'Kubus', arUrl: 'https://app-edu.assemblrworld.com/en/creation/-eGQgkYkAKlbGegmVGej', page: 1, description: 'Model 3D kubus yang sesuai dengan bagian bangunan Candi Jawi.', provider: 'Assemblr' },
    { id: 'komik1-model-2', title: 'Balok', arUrl: 'https://app-edu.assemblrworld.com/en/creation/-hwhAtiZhyCivpQ2Jl5Z', page: 2, description: 'Model 3D balok yang sesuai dengan bagian struktur Candi Jawi.', provider: 'Assemblr' },
    { id: 'komik1-model-3', title: 'Prisma Segi Empat', arUrl: 'https://app-edu.assemblrworld.com/en/creation/-PdcSjQ4sYkREdgHK3rX', page: 3, description: 'Model 3D prisma segi empat yang sesuai dengan bagian ornamen candi.', provider: 'Assemblr' },
    { id: 'komik1-model-4', title: 'Limas Segi Empat', arUrl: 'https://app-edu.assemblrworld.com/en/creation/-499KAWhzbvlKt5wECkt', page: 4, description: 'Model 3D limas segi empat yang sesuai dengan bagian puncak candi.', provider: 'Assemblr' },
    { id: 'komik1-model-5', title: 'Kerucut', arUrl: 'https://app-edu.assemblrworld.com/en/creation/-HE74wRR8CK9nJFAybzt', page: 5, description: 'Model 3D kerucut yang sesuai dengan bagian puncak yang meruncing.', provider: 'Assemblr' },
  ],
  aiPrompt: {
    navigation: 'Gunakan bahasa sederhana untuk menjelaskan setiap bangun ruang yang diamati pada komik.',
    objectTutor: 'Bantu siswa menghubungkan ciri bangun ruang dengan bagian candi yang terlihat.',
    application: 'Bantu siswa menerapkan pemahaman bangun ruang pada situasi baru yang serupa.',
    argumentation: 'Anda adalah guru SD yang mengevaluasi argumentasi siswa. Periksa apakah siswa: (1) Memahami hubungan antara bagian candi dengan bangun ruang yang dipilih, (2) Dapat menjelaskan alasan dengan logis, (3) Menyebutkan ciri-ciri bangun ruang yang relevan. Berikan feedback tentang kekuatan dan area yang perlu diperbaiki. Jangan memberikan jawaban lengkap. Berikan skor 1-5 dan tentukan level: SANGAT_BAIK (skor 5), HAMPIR_BENAR (skor 3-4), atau PERLU_PERBAIKAN (skor 1-2). Gunakan respons JSON dengan field: level, score, feedback, strength, improvement, suggestion.',
    resolution: 'Bimbing siswa menyelesaikan soal numerasi dari bangun ruang yang dipelajari.',
    introspection: 'Buat refleksi singkat yang menekankan pemahaman dan rasa percaya diri.',
  },
  identification: {
    questions: [
      {
        id: 'komik1-ident-1',
        question: 'Apa saja bangun ruang yang kamu temukan pada komik ini?',
        image: identKubus.src,
        imageAlt: 'Foto keseluruhan Candi Jawi dengan overlay bangun ruang dominan.',
        overlayType: identKubus.src,
        options: [
          { text: 'Kubus', correct: true },
          { text: 'Balok', correct: true },
          { text: 'Prisma Segi Empat', correct: true },
          { text: 'Limas Segi Empat', correct: true },
          { text: 'Kerucut', correct: true },
        ],
        explanation: 'Pada komik ini, beberapa bangun ruang utama yang terlihat adalah kubus, balok, prisma, limas, dan kerucut.',
      },
      {
        id: 'komik1-ident-2',
        question: 'Bangun ruang mana yang paling cocok untuk menggambarkan pilar utama?',
        image: identBalok.src,
        imageAlt: 'Zoom bagian kaki Candi Jawi.',
        overlayType: identBalok.src,
        options: [
          { text: 'Kubus', correct: true },
          { text: 'Balok', correct: false },
          { text: 'Kerucut', correct: false },
          { text: 'Tabung', correct: false },
        ],
        explanation: 'Pilar utama candi sering tersusun dari bentuk kotak, sehingga kubus cocok untuk memodelkannya.',
      },
      {
        id: 'komik1-ident-3',
        question: 'Bagian badan candi paling mirip dengan bangun ruang apa?',
        image: identPrisma.src,
        imageAlt: 'Zoom badan tengah Candi Jawi.',
        overlayType: identPrisma.src,
        options: [
          { text: 'Balok', correct: true },
          { text: 'Prisma Segi Empat', correct: false },
          { text: 'Bola', correct: false },
          { text: 'Tabung', correct: false },
        ],
        explanation: 'Badan candi menyerupai bangun ruang balok.',
      },
      {
        id: 'komik1-ident-4',
        question: 'Struktur puncak yang meruncing bisa diterangkan dengan bangun ruang apa?',
        image: identLimas.src,
        imageAlt: 'Zoom atap Candi Jawi.',
        overlayType: identLimas.src,
        options: [
          { text: 'Limas Segi Empat', correct: true },
          { text: 'Kerucut', correct: true },
          { text: 'Kubus', correct: false },
          { text: 'Bola', correct: false },
        ],
        explanation: 'Puncak candi meniru limas dan kerucut karena meruncing ke satu titik.',
      },
    ],
    feedback: {
      complete: 'Hebat! Kamu berhasil mengidentifikasi bangun ruang yang dipelajari pada komik ini.',
      partial: 'Ada beberapa jawaban yang masih perlu diperiksa lagi.',
      incomplete: 'Perhatikan kembali bagian komik untuk menemukan bentuk yang paling sesuai.',
    },
  },
  application: {
    title: 'Terapkan Ilmu di Konteks Baru',
    intro: 'Amati objek dari sudut berbeda dan pilih bangun ruang yang paling cocok.',
    prompt: 'Pilih bangun ruang yang paling cocok untuk menjelaskan objek yang kamu lihat dan jelaskan alasanmu.',
    context: 'Objek baru yang menyimpan bentuk serupa dengan bangun ruang yang dipelajari di candi.',
    images: [
      { src: appAtap.src, alt: 'Tampak depan', label: 'Tampak Depan', description: 'Perhatikan bentuk utama dari depan.' },
      { src: appOrnament.src, alt: 'Detail ornamen', label: 'Detail Ornamen', description: 'Perhatikan ornamen dan detailnya.' },
      { src: appTangga.src, alt: 'Tangga candi', label: 'Tangga', description: 'Perhatikan bentuk tangga dan sudutnya.' },
    ],
    options: [
      { value: 'Kubus', label: 'Kubus' },
      { value: 'Balok', label: 'Balok' },
      { value: 'Prisma Segi Empat', label: 'Prisma Segi Empat' },
      { value: 'Limas Segi Empat', label: 'Limas Segi Empat' },
      { value: 'Kerucut', label: 'Kerucut' },
    ],
  },
  argumentation: {
    questions: [
      {
        id: 'komik1-arg-badan-candi',
        title: 'Bagian Badan Candi',
        templePart: 'Badan Candi',
        question: 'Mengapa bagian badan Candi Jawi dapat dimodelkan sebagai kubus?',
        photoSrc: argKubus.src,
        image: argKubus.src,
        argumentationPhoto: identKubus.src,
        argumentationHighlight: argKubus.src,
        argumentationPrompt: 'Jelaskan mengapa badan candi bisa dimodelkan sebagai kubus, sebutkan ciri sisi dan rusuknya, serta hubungkan dengan foto yang diberikan.',
        argumentationQuestion: 'Mengapa bagian badan Candi Jawi dapat dimodelkan sebagai kubus?',
        argumentationTitle: 'Bagian Badan Candi',
        photoAlt: 'Bagian badan Candi Jawi.',
        shape: 'Kubus',
        shapeName: 'Kubus',
        shapeKey: 'kubus',
        shapeSrc: navKubus.src,
        icon: navKubus.src,
        aiContext: 'Jelaskan mengapa badan candi bisa dimodelkan sebagai kubus, dan sebutkan ciri sisi serta rusuknya.',
        feedback: 'Bagus! Badan candi terlihat seperti bangun ruang kotak dengan sisi-sisi sejajar dan rusuk yang tegas, sehingga cocok dimodelkan sebagai kubus.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik1-arg-tangga-candi',
        title: 'Bagian Tangga Candi',
        templePart: 'Tangga Candi',
        question: 'Mengapa bagian tangga Candi Jawi dapat dimodelkan sebagai balok?',
        photoSrc: argBalok.src,
        image: argBalok.src,
        argumentationPhoto: identPrisma.src,
        argumentationHighlight: argBalok.src,
        argumentationPrompt: 'Jelaskan mengapa tangga candi dapat dilihat sebagai balok, bandingkan panjang, lebar, dan tinggi dengan foto.',
        argumentationQuestion: 'Mengapa bagian tangga Candi Jawi dapat dimodelkan sebagai balok?',
        argumentationTitle: 'Bagian Tangga Candi',
        photoAlt: 'Bagian tangga Candi Jawi.',
        shape: 'Balok',
        shapeName: 'Balok',
        shapeKey: 'balok',
        shapeSrc: navBalok.src,
        icon: navBalok.src,
        aiContext: 'Jelaskan mengapa tangga candi dapat dilihat sebagai balok dan sebutkan panjang, lebar, dan tinggi yang membedakannya dari kubus.',
        feedback: 'Bagus! Tangga candi memiliki bentuk memanjang dengan tiga ukuran berbeda, jadi balok adalah bangun ruang yang tepat untuk menggambarkannya.',
        highlightColor: 'border-amber-500',
      },
      {
        id: 'komik1-arg-ornamen-candi',
        title: 'Bagian Ornamen Candi',
        templePart: 'Ornamen Candi',
        question: 'Mengapa bagian ornamen Candi Jawi dapat dimodelkan sebagai prisma segi empat?',
        photoSrc: argPrisma.src,
        image: argPrisma.src,
        argumentationPhoto: identPrisma.src,
        argumentationHighlight: argPrisma.src,
        argumentationPrompt: 'Jelaskan mengapa ornamen candi cocok dimodelkan sebagai prisma segi empat dan hubungkan dengan foto.',
        argumentationQuestion: 'Mengapa bagian ornamen Candi Jawi dapat dimodelkan sebagai prisma segi empat?',
        argumentationTitle: 'Bagian Ornamen Candi',
        photoAlt: 'Bagian ornamen Candi Jawi.',
        shape: 'Prisma Segi Empat',
        shapeName: 'Prisma Segi Empat',
        shapeKey: 'prisma',
        shapeSrc: navPrismaPreview.src,
        icon: navPrismaPreview.src,
        aiContext: 'Jelaskan mengapa ornamen candi cocok dimodelkan sebagai prisma segi empat, dan tunjukkan hubungan antara alas dan sisi tegaknya.',
        feedback: 'Bagus! Ornamen candi memiliki alas dan sisi tegak yang sejajar sehingga cocok sebagai prisma segi empat.',
        highlightColor: 'border-cyan-500',
      },
      {
        id: 'komik1-arg-puncak-candi',
        title: 'Bagian Puncak Candi',
        templePart: 'Puncak Candi',
        question: 'Mengapa bagian puncak Candi Jawi dapat dimodelkan sebagai limas segi empat?',
        photoSrc: argLimas.src,
        image: argLimas.src,
        argumentationPhoto: identLimas.src,
        argumentationHighlight: argLimas.src,
        argumentationPrompt: 'Jelaskan mengapa puncak candi dapat dimodelkan sebagai limas segi empat, sebutkan alas dan sisi-sisi segitiga.',
        argumentationQuestion: 'Mengapa bagian puncak Candi Jawi dapat dimodelkan sebagai limas segi empat?',
        argumentationTitle: 'Bagian Puncak Candi',
        photoAlt: 'Bagian puncak Candi Jawi.',
        shape: 'Limas Segi Empat',
        shapeName: 'Limas Segi Empat',
        shapeKey: 'limas',
        shapeSrc: navDefault.src,
        icon: navDefault.src,
        aiContext: 'Jelaskan mengapa puncak candi dapat dilihat sebagai limas segi empat, dan sebutkan alas serta sisi-sisi segitiga yang membentuknya.',
        feedback: 'Bagus! Puncak candi memiliki alas segi empat dan sisi-sisi yang bertemu di satu titik puncak, sehingga sesuai dengan limas segi empat.',
        highlightColor: 'border-secondary-500',
      },
      {
        id: 'komik1-arg-ornamen-puncak',
        title: 'Bagian Ornamen Puncak',
        templePart: 'Ornamen Puncak',
        question: 'Mengapa ornamen puncak Candi Jawi dapat dimodelkan sebagai kerucut?',
        photoSrc: argKerucut.src,
        image: argKerucut.src,
        argumentationPhoto: identLimas.src,
        argumentationHighlight: argKerucut.src,
        argumentationPrompt: 'Jelaskan mengapa ornamen puncak cocok dimodelkan sebagai kerucut dan sebutkan ciri alas bundar serta puncaknya.',
        argumentationQuestion: 'Mengapa ornamen puncak Candi Jawi dapat dimodelkan sebagai kerucut?',
        argumentationTitle: 'Bagian Ornamen Puncak',
        photoAlt: 'Bagian ornamen puncak Candi Jawi.',
        shape: 'Kerucut',
        shapeName: 'Kerucut',
        shapeKey: 'kerucut',
        shapeSrc: navKerucut.src,
        icon: navKerucut.src,
        aiContext: 'Jelaskan mengapa ornamen puncak cocok dimodelkan sebagai kerucut dan sebutkan ciri alas bundar serta puncaknya.',
        feedback: 'Bagus! Ornamen puncak candi meruncing dan memiliki bentuk yang paling mirip dengan kerucut.',
        highlightColor: 'border-secondary-500',
      },
    ],
  },
  resolution: {
    missions: [
      {
        id: 1,
        title: 'Misi 1 · Volume Kubus',
        part: 'Pilar Utama',
        shape: 'Kubus',
        prompt: 'Sebuah kubus memiliki panjang rusuk 8 cm. Berapa volumenya?',
        options: [
          { key: 'A', label: '256 cm³' },
          { key: 'B', label: '384 cm³' },
          { key: 'C', label: '512 cm³' },
          { key: 'D', label: '640 cm³' },
        ],
        correctKey: 'C',
        answer: '512 cm³',
        formula: 'V = s × s × s = 8 × 8 × 8 = 512 cm³',
        explanation: 'Kubus memiliki rusuk yang sama panjang, sehingga volumenya adalah perkalian sisi tiga kali.',
        aiHint: 'Gunakan rumus volume kubus: V = s³.',
        context: 'Pilar utama candi dapat dipandang sebagai susunan kubus yang padat.',
        accent: 'from-primary-600 to-primary-700',
        illustration: navKubus.src,
      },
      {
        id: 2,
        title: 'Misi 2 · Volume Balok',
        part: 'Badan Candi',
        shape: 'Balok',
        prompt: 'Sebuah balok panjang 10 cm, lebar 6 cm, tinggi 8 cm. Berapa volumenya?',
        options: [
          { key: 'A', label: '360 cm³' },
          { key: 'B', label: '420 cm³' },
          { key: 'C', label: '480 cm³' },
          { key: 'D', label: '520 cm³' },
        ],
        correctKey: 'C',
        answer: '480 cm³',
        formula: 'V = p × l × t = 10 × 6 × 8 = 480 cm³',
        explanation: 'Balok memiliki tiga ukuran berbeda, yaitu panjang, lebar, dan tinggi.',
        aiHint: 'Kalikan panjang, lebar, dan tinggi dengan hati-hati.',
        context: 'Badan candi menyerupai balok yang memanjang ke atas.',
        accent: 'from-secondary-500 to-secondary-600',
        illustration: navBalok.src,
      },
    ],
  },
  introspection: {
    checklist: [
      'Saya memahami bangun ruang yang muncul pada komik ini.',
      'Saya dapat menjelaskan ciri-ciri kubus, balok, prisma, limas, dan kerucut.',
      'Saya percaya diri mengerjakan soal serupa tentang volume.',
    ],
    completionMessage: 'Kamu telah menyelesaikan pembelajaran komik ini dengan baik.',
    nextPrompt: 'Lanjutkan ke komik berikutnya untuk belajar lagi.',
  },
  report: {
    summary: 'Laporan ini menampilkan hasil pemahamanmu terhadap bangun ruang pada komik.',
    learnedShapes: ['Kubus', 'Balok', 'Prisma Segi Empat', 'Limas Segi Empat', 'Kerucut'],
  },
};
