import type { ComicContentPackageLike } from '../../types';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 1,
    title: 'Petualangan Bangun Ruang Candi Jawi',
    subtitle: 'Etnomatematika Bangun Ruang',
    location: 'Candi Jawi, Pasuruan',
    classLevel: 'VI',
    cover: '/comics/komik-1/cover.png',
    thumbnail: '/comics/komik-1/thumbnail.png',
    learningTargets: [
      'Mengamati bentuk pada komik',
      'Menghubungkan konsep bangun ruang dengan objek nyata',
      'Menggunakan alasan matematis untuk menjelaskan pola',
    ],
    synopsis: 'Pembelajaran CINARAI yang dapat dipakai untuk berbagai komik.',
  },
  learningObjects: [
    {
      id: 'komik1-kubus',
      title: 'Kubus',
      description: 'Bentuk kotak pada bagian pilar utama candi.',
      page: 1,
      qrImage: '/assets/qr/komik-1/13-kubus.jpeg',
      objectImage: '/images/identification/komik1-soal1.jpg',
      modelUrl: 'https://modelviewer.dev/examples/scenegraph/index.html',
      embedUrl: 'https://modelviewer.dev/examples/scenegraph/index.html',
      viewerType: 'embed',
      provider: 'ModelViewer',
      aiPrompt: 'Jelaskan ciri kubus, sisi, rusuk, dan titik sudut yang terlihat pada objek ini.',
      question: 'Apa ciri khas kubus yang terlihat pada objek ini?',
      answer: 'Kubus memiliki 6 sisi persegi, 12 rusuk, dan 8 titik sudut.',
      feedback: 'Benar, kubus bisa dikenali dari sisi-sisinya yang sama besar dan bentuk persegi.',
    },
    {
      id: 'komik1-balok',
      title: 'Balok',
      description: 'Bentuk persegi panjang yang menyusun badan candi.',
      page: 2,
      qrImage: '/assets/qr/komik-1/16-balok.jpeg',
      objectImage: '/images/identification/komik1-soal3.jpg',
      modelUrl: 'https://modelviewer.dev/examples/scenegraph/index.html',
      embedUrl: 'https://modelviewer.dev/examples/scenegraph/index.html',
      viewerType: 'embed',
      provider: 'ModelViewer',
      aiPrompt: 'Jelaskan perbedaan balok dengan kubus berdasarkan panjang, lebar, dan tinggi.',
      question: 'Bagaimana cara membedakan balok dengan kubus?',
      answer: 'Balok memiliki sisi-sisi berbentuk persegi panjang, sedangkan kubus semua sisinya sama.',
      feedback: 'Bagus, balok dapat dikenali dari sisi-sisi yang tidak semuanya sama panjang.',
    },
    {
      id: 'komik1-prisma',
      title: 'Prisma Segi Empat',
      description: 'Bentuk prisma pada sisi bangunan yang tegak.',
      page: 3,
      qrImage: '/assets/qr/komik-1/22-prisma.jpeg',
      objectImage: '/images/identification/komik1-soal5.jpg',
      modelUrl: 'https://modelviewer.dev/examples/scenegraph/index.html',
      embedUrl: 'https://modelviewer.dev/examples/scenegraph/index.html',
      viewerType: 'embed',
      provider: 'ModelViewer',
      aiPrompt: 'Jelaskan alas, tutup, dan sisi tegak prisma segi empat.',
      question: 'Apa saja bagian utama prisma segi empat?',
      answer: 'Prisma segi empat memiliki dua alas yang sejajar dan sisi tegak berbentuk persegi panjang.',
      feedback: 'Benar, prisma segi empat mudah dikenali dari dua alas dan sisi tegak yang membentuk bidang.',
    },
    {
      id: 'komik1-limas',
      title: 'Limas Segi Empat',
      description: 'Puncak bangunan yang meruncing ke satu titik.',
      page: 4,
      qrImage: '/assets/qr/komik-1/17-limas.jpeg',
      objectImage: '/images/identification/komik1-soal4.jpg',
      modelUrl: 'https://modelviewer.dev/examples/scenegraph/index.html',
      embedUrl: 'https://modelviewer.dev/examples/scenegraph/index.html',
      viewerType: 'embed',
      provider: 'ModelViewer',
      aiPrompt: 'Jelaskan bentuk alas dan sisi tegak limas segi empat.',
      question: 'Mengapa limas segi empat punya puncak tajam?',
      answer: 'Karena semua sisi tegak bertemu di satu titik puncak.',
      feedback: 'Betul, limas segi empat memiliki satu puncak dan alas berbentuk segi empat.',
    },
    {
      id: 'komik1-kerucut',
      title: 'Kerucut',
      description: 'Bagian atap yang meruncing ke atas.',
      page: 5,
      qrImage: '/assets/qr/komik-1/28-kerucut.jpeg',
      objectImage: '/images/identification/komik1-soal4.jpg',
      modelUrl: 'https://modelviewer.dev/examples/scenegraph/index.html',
      embedUrl: 'https://modelviewer.dev/examples/scenegraph/index.html',
      viewerType: 'embed',
      provider: 'ModelViewer',
      aiPrompt: 'Jelaskan ciri kerucut dan hubungan antara alas, tinggi, dan sisi miring.',
      question: 'Apa ciri utama kerucut?',
      answer: 'Kerucut memiliki alas lingkaran dan satu titik puncak.',
      feedback: 'Ya, kerucut bisa dikenali dari alas bundar dan bentuk yang meruncing ke atas.',
    },
  ],
  qrCode: [
    { id: 'komik1-qr-1', imageSrc: '/assets/qr/komik-1/13-kubus.jpeg', alt: 'QR Kubus', label: 'Kubus', description: 'Scan untuk membuka model 3D kubus.' },
    { id: 'komik1-qr-2', imageSrc: '/assets/qr/komik-1/16-balok.jpeg', alt: 'QR Balok', label: 'Balok', description: 'Scan untuk membuka model 3D balok.' },
    { id: 'komik1-qr-3', imageSrc: '/assets/qr/komik-1/22-prisma.jpeg', alt: 'QR Prisma', label: 'Prisma', description: 'Scan untuk membuka model 3D prisma.' },
    { id: 'komik1-qr-4', imageSrc: '/assets/qr/komik-1/17-limas.jpeg', alt: 'QR Limas', label: 'Limas', description: 'Scan untuk membuka model 3D limas.' },
    { id: 'komik1-qr-5', imageSrc: '/assets/qr/komik-1/28-kerucut.jpeg', alt: 'QR Kerucut', label: 'Kerucut', description: 'Scan untuk membuka model 3D kerucut.' },
  ],
  model3D: [
    { id: 'komik1-model-1', title: 'Kubus', arUrl: 'https://modelviewer.dev/examples/scenegraph/index.html', page: 1, description: 'Model 3D kubus untuk pengamatan sisi dan rusuk.' },
    { id: 'komik1-model-2', title: 'Balok', arUrl: 'https://modelviewer.dev/examples/scenegraph/index.html', page: 2, description: 'Model 3D balok untuk pengamatan panjang, lebar, dan tinggi.' },
    { id: 'komik1-model-3', title: 'Prisma Segi Empat', arUrl: 'https://modelviewer.dev/examples/scenegraph/index.html', page: 3, description: 'Model 3D prisma segi empat.' },
    { id: 'komik1-model-4', title: 'Limas Segi Empat', arUrl: 'https://modelviewer.dev/examples/scenegraph/index.html', page: 4, description: 'Model 3D limas segi empat.' },
    { id: 'komik1-model-5', title: 'Kerucut', arUrl: 'https://modelviewer.dev/examples/scenegraph/index.html', page: 5, description: 'Model 3D kerucut.' },
  ],
  aiPrompt: {
    navigation: 'Gunakan bahasa sederhana untuk menjelaskan setiap bangun ruang yang diamati pada komik.',
    objectTutor: 'Bantu siswa menghubungkan ciri bangun ruang dengan bagian candi yang terlihat.',
    application: 'Bantu siswa menerapkan pemahaman bangun ruang pada situasi baru yang serupa.',
    argumentation: 'Berikan umpan balik tentang alasan siswa yang menjelaskan bentuk bangun ruang dari pengamatan.',
    resolution: 'Bimbing siswa menyelesaikan soal numerasi dari bangun ruang yang dipelajari.',
    introspection: 'Buat refleksi singkat yang menekankan pemahaman dan rasa percaya diri.',
  },
  identification: {
    questions: [
      {
        id: 'komik1-ident-1',
        question: 'Apa saja bangun ruang yang kamu temukan pada komik ini?',
        image: '/images/identification/komik1-soal1.jpg',
        imageAlt: 'Foto keseluruhan Candi Jawi dengan overlay bangun ruang dominan.',
        overlayType: '/images/identification/komik1-soal1-tubuh-candi.svg',
        options: [
          { text: 'Kubus', correct: true },
          { text: 'Balok', correct: true },
          { text: 'Prisma Segi Empat', correct: true },
          { text: 'Limas Segi Empat', correct: true },
          { text: 'Kerucut', correct: true },
        ],
        explanation: 'Pada komik ini, beberapa bangun ruang utama yang terlihat adalah kubus, balok, prisma, limas, dan kerucut.',
      },
      {
        id: 'komik1-ident-2',
        question: 'Bangun ruang mana yang paling cocok untuk menggambarkan pilar utama?',
        image: '/images/identification/komik1-soal2.jpg',
        imageAlt: 'Zoom bagian kaki Candi Jawi.',
        overlayType: '/images/identification/komik1-soal2-kaki-candi.svg',
        options: [
          { text: 'Kubus', correct: true },
          { text: 'Balok', correct: false },
          { text: 'Prisma Segi Empat', correct: false },
          { text: 'Limas Segi Empat', correct: false },
          { text: 'Kerucut', correct: false },
        ],
        explanation: 'Pilar utama candi sering tersusun dari bentuk kotak, sehingga kubus cocok untuk memodelkannya.',
      },
      {
        id: 'komik1-ident-3',
        question: 'Bagian badan candi paling mirip dengan bangun ruang apa?',
        image: '/images/identification/komik1-soal3.jpg',
        imageAlt: 'Zoom badan tengah Candi Jawi.',
        overlayType: '/images/identification/komik1-soal3-puncak-candi.svg',
        options: [
          { text: 'Balok', correct: true },
          { text: 'Kubus', correct: false },
          { text: 'Prisma Segi Empat', correct: false },
          { text: 'Limas Segi Empat', correct: false },
          { text: 'Kerucut', correct: false },
        ],
        explanation: 'Badan candi menyerupai bangun ruang balok.',
      },
      {
        id: 'komik1-ident-4',
        question: 'Struktur puncak yang meruncing bisa diterangkan dengan bangun ruang apa?',
        image: '/images/identification/komik1-soal4.jpg',
        imageAlt: 'Zoom atap Candi Jawi.',
        overlayType: '/images/identification/komik1-soal4-atap-candi.svg',
        options: [
          { text: 'Limas Segi Empat', correct: true },
          { text: 'Kerucut', correct: true },
          { text: 'Kubus', correct: false },
          { text: 'Balok', correct: false },
          { text: 'Prisma Segi Empat', correct: false },
        ],
        explanation: 'Puncak candi meniru limas dan kerucut karena meruncing ke satu titik.',
      },
    ],
    feedback: {
      complete: 'Hebat! Kamu berhasil mengidentifikasi bangun ruang yang dipelajari pada komik ini.',
      partial: 'Ada beberapa jawaban yang masih perlu diperiksa lagi.',
      incomplete: 'Perhatikan kembali bagian komik untuk menemukan bentuk yang paling sesuai.',
    },
  },
  application: {
    title: 'Terapkan Ilmu di Konteks Baru',
    intro: 'Amati objek dari sudut berbeda dan pilih bangun ruang yang paling cocok.',
    prompt: 'Pilih bangun ruang yang paling cocok untuk menjelaskan objek yang kamu lihat dan jelaskan alasanmu.',
    context: 'Objek baru yang menyimpan bentuk serupa dengan bangun ruang yang dipelajari di candi.',
    images: [
      { src: '/images/identification/komik1-soal1.jpg', alt: 'Tampak depan', label: 'Tampak Depan', description: 'Perhatikan bentuk utama dari depan.' },
      { src: '/images/identification/komik1-soal3.jpg', alt: 'Sudut puncak', label: 'Sudut Puncak', description: 'Perhatikan bentuk puncak yang meruncing.' },
      { src: '/images/identification/komik1-soal5.jpg', alt: 'Sudut samping', label: 'Sudut Samping', description: 'Perhatikan sisi samping dan bentuk bidangnya.' },
    ],
    options: [
      { value: 'Kubus', label: 'Kubus' },
      { value: 'Balok', label: 'Balok' },
      { value: 'Prisma Segi Empat', label: 'Prisma Segi Empat' },
      { value: 'Limas Segi Empat', label: 'Limas Segi Empat' },
      { value: 'Kerucut', label: 'Kerucut' },
    ],
  },
  argumentation: {
    questions: [
      {
        id: 'komik1-arg-1',
        templePart: 'pilar utama',
        question: 'Mengapa pilar utama dapat dimodelkan sebagai kubus atau balok?',
        photoSrc: '/images/identification/komik1-soal1.jpg',
        photoAlt: 'Pilar utama candi terlihat kokoh dan kotak.',
        shapeName: 'Kubus',
        shapeKey: 'kubus',
        shapeSrc: '/images/navigation/kubus.svg',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik1-arg-2',
        templePart: 'atap',
        question: 'Mengapa sisi atap dapat dianggap sebagai limas?',
        photoSrc: '/images/identification/komik1-soal4.jpg',
        photoAlt: 'Atap candi tampak meruncing.',
        shapeName: 'Limas Segi Empat',
        shapeKey: 'limas',
        shapeSrc: '/images/navigation/limas.svg',
        highlightColor: 'border-accent-500',
      },
    ],
  },
  resolution: {
    missions: [
      {
        id: 1,
        title: 'Misi 1 · Volume Kubus',
        part: 'Pilar Utama',
        shape: 'Kubus',
        prompt: 'Sebuah kubus memiliki panjang rusuk 8 cm. Berapa volumenya?',
        options: [
          { key: 'A', label: '256 cm³' },
          { key: 'B', label: '384 cm³' },
          { key: 'C', label: '512 cm³' },
          { key: 'D', label: '640 cm³' },
        ],
        correctKey: 'C',
        answer: '512 cm³',
        formula: 'V = s × s × s = 8 × 8 × 8 = 512 cm³',
        explanation: 'Kubus memiliki rusuk yang sama panjang, sehingga volumenya adalah perkalian sisi tiga kali.',
        aiHint: 'Gunakan rumus volume kubus: V = s³.',
        context: 'Pilar utama candi dapat dipandang sebagai susunan kubus yang padat.',
        accent: 'from-primary-600 to-primary-700',
        illustration: '/images/navigation/kubus.svg',
      },
      {
        id: 2,
        title: 'Misi 2 · Volume Balok',
        part: 'Badan Candi',
        shape: 'Balok',
        prompt: 'Sebuah balok panjang 10 cm, lebar 6 cm, tinggi 8 cm. Berapa volumenya?',
        options: [
          { key: 'A', label: '360 cm³' },
          { key: 'B', label: '420 cm³' },
          { key: 'C', label: '480 cm³' },
          { key: 'D', label: '520 cm³' },
        ],
        correctKey: 'C',
        answer: '480 cm³',
        formula: 'V = p × l × t = 10 × 6 × 8 = 480 cm³',
        explanation: 'Balok memiliki tiga ukuran berbeda, yaitu panjang, lebar, dan tinggi.',
        aiHint: 'Kalikan panjang, lebar, dan tinggi dengan hati-hati.',
        context: 'Badan candi menyerupai balok yang memanjang ke atas.',
        accent: 'from-secondary-500 to-secondary-600',
        illustration: '/images/navigation/balok.svg',
      },
    ],
  },
  introspection: {
    checklist: [
      'Saya memahami bangun ruang yang muncul pada komik ini.',
      'Saya dapat menjelaskan ciri-ciri kubus, balok, prisma, limas, dan kerucut.',
      'Saya percaya diri mengerjakan soal serupa tentang volume.',
    ],
    completionMessage: 'Kamu telah menyelesaikan pembelajaran komik ini dengan baik.',
    nextPrompt: 'Lanjutkan ke komik berikutnya untuk belajar lagi.',
  },
  report: {
    summary: 'Laporan ini menampilkan hasil pemahamanmu terhadap bangun ruang pada komik.',
    learnedShapes: ['Kubus', 'Balok', 'Prisma Segi Empat', 'Limas Segi Empat', 'Kerucut'],
  },
};
