import type { ComicContentPackageLike } from '../../types';
import coverImg from '@/features/comics/comic-2/assets/cover/cover.png';
import thumbnailImg from '@/features/comics/comic-2/assets/cover/thumbnail.png';
import navUmpang from '@/features/comics/comic-2/assets/navigation/umpang.png';
import navBaleAgung from '@/features/comics/comic-2/assets/navigation/bale-agung.png';
import navMensir from '@/features/comics/comic-2/assets/navigation/mensir.png';
import navReliefLingkaran from '@/features/comics/comic-2/assets/navigation/relief-lingkaran.png';
import navTangga from '@/features/comics/comic-2/assets/navigation/tangga.png';
import navGapura from '@/features/comics/comic-2/assets/navigation/gapura.png';
import qr13 from '@/features/comics/comic-2/assets/qr/13-objek-1.jpeg';
import qr15 from '@/features/comics/comic-2/assets/qr/15-objek-2.jpeg';
import qr17 from '@/features/comics/comic-2/assets/qr/17-objek-3.jpeg';
import qr18 from '@/features/comics/comic-2/assets/qr/18-objek-4.jpeg';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 2,
    title: 'Petualangan Simetri Candi Penataran',
    subtitle: 'Etnomatematika Bangun Datar',
    location: 'Candi Penataran, Blitar',
    classLevel: 'V',
    cover: coverImg.src,
    thumbnail: thumbnailImg.src,
    learningTargets: [
      'Mengamati objek yang muncul di Candi Penataran.',
      'Menghubungkan bangun datar dengan bentuk nyata pada candi.',
      'Menggunakan bahasa sederhana untuk menjelaskan simetri dan pola.',
    ],
    synopsis: 'Pembelajaran untuk bangun datar di Candi Penataran.',
  },
  learningObjects: [
    {
      id: 'komik2-umpang',
      title: 'Umpang',
      description: 'Bagian rumah adat yang terlihat panjang dan seimbang pada Candi Penataran.',
      page: 1,
      qrImage: qr15.src,
      qrTitle: 'Umpang',
      qrDescription: 'Lihat bentuk panjang dan seimbang pada Umpang.',
      navImage: navUmpang.src,
      objectImage: navUmpang.src,
      image: navUmpang.src,
      model3DUrl: 'https://asblr.com/MmAMdg',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Bentuk permukaan Umpang menyerupai persegi panjang. Amati sisi panjang dan pendeknya dengan hati-hati.',
      question: 'Bagaimana bentuk Umpang terlihat?',
      answer: 'Umpang terlihat seperti persegi panjang yang panjang dan seimbang.',
      simpleExplanation: 'Umpang terlihat seperti persegi panjang yang panjang dan seimbang.',
      feedback: 'Benar, Umpang dapat dipelajari sebagai contoh bangun datar persegi panjang.',
      shapeKey: 'persegi-panjang',
      shapeName: 'Persegi Panjang',
      shape: 'Persegi Panjang',
      symmetryConnection: 'Sisi kiri dan kanan Umpang membantu kita melihat keseimbangan bentuk pada candi.',
      symmetryRelation: 'Sisi kiri dan kanan Umpang membantu kita melihat keseimbangan bentuk pada candi.',
    },
    {
      id: 'komik2-bale-agung',
      title: 'Bale Agung',
      description: 'Bagian bangunan yang tampak luas dan rapi pada Candi Penataran.',
      page: 2,
      qrImage: qr13.src,
      qrTitle: 'Bale Agung',
      qrDescription: 'Amati bidang panjang yang tampak pada Bale Agung.',
      navImage: navBaleAgung.src,
      objectImage: navBaleAgung.src,
      image: navBaleAgung.src,
      model3DUrl: 'https://asblr.com/yvcuaW',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Bale Agung punya bidang yang tampak panjang dan membentuk persegi panjang. Perhatikan sisi-sisinya.',
      question: 'Apa bangun datar yang paling terlihat pada Bale Agung?',
      answer: 'Bale Agung tampak seperti persegi panjang.',
      simpleExplanation: 'Bale Agung tampak seperti persegi panjang.',
      feedback: 'Bagus, bale agung dapat kita pelajari sebagai contoh persegi panjang.',
      shapeKey: 'persegi-panjang',
      shapeName: 'Persegi Panjang',
      shape: 'Persegi Panjang',
      symmetryConnection: 'Bale Agung membantu kita melihat bahwa bentuk yang seimbang sering muncul pada bangunan.',
      symmetryRelation: 'Bale Agung membantu kita melihat bahwa bentuk yang seimbang sering muncul pada bangunan.',
    },
    {
      id: 'komik2-candi-angka',
      title: 'Candi Angka',
      description: 'Bagian candi yang menampilkan bentuk runcing dan simetris pada Candi Penataran.',
      page: 3,
      qrImage: qr17.src,
      qrTitle: 'Candi Angka',
      qrDescription: 'Perhatikan bentuk runcing dan simetris pada Candi Angka.',
      navImage: navGapura.src,
      objectImage: navGapura.src,
      image: navGapura.src,
      model3DUrl: 'https://asblr.com/ljcPsy',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Candi Angka memiliki bentuk yang mirip segitiga sama kaki. Perhatikan sisi-sisi yang sama panjang.',
      question: 'Bangun datar apa yang terlihat pada Candi Angka?',
      answer: 'Candi Angka tampak seperti segitiga sama kaki.',
      simpleExplanation: 'Candi Angka tampak seperti segitiga sama kaki.',
      feedback: 'Benar, bentuknya bisa dipelajari sebagai segitiga sama kaki.',
      shapeKey: 'segitiga-sama-kaki',
      shapeName: 'Segitiga Sama Kaki',
      shape: 'Segitiga Sama Kaki',
      symmetryConnection: 'Bentuknya terlihat seimbang ketika dibagi menjadi dua bagian yang sama.',
      symmetryRelation: 'Bentuknya terlihat seimbang ketika dibagi menjadi dua bagian yang sama.',
    },
    {
      id: 'komik2-mensir',
      title: 'Mensir',
      description: 'Bagian ornamen yang tampak seperti persegi dan berhubungan dengan simetri pada Candi Penataran.',
      page: 4,
      qrImage: qr13.src,
      qrTitle: 'Mensir',
      qrDescription: 'Bandingkan pola persegi yang berulang pada Mensir.',
      navImage: navMensir.src,
      objectImage: navMensir.src,
      image: navMensir.src,
      model3DUrl: 'https://asblr.com/yvcuaW',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Mensir bisa diamati sebagai pola persegi yang berulang dan rapi pada candi.',
      question: 'Apa bangun datar yang terlihat pada Mensir?',
      answer: 'Mensir terlihat seperti persegi.',
      simpleExplanation: 'Mensir terlihat seperti persegi.',
      feedback: 'Bagus, mensir membantu kita mengenali bangun datar persegi.',
      shapeKey: 'persegi',
      shapeName: 'Persegi',
      shape: 'Persegi',
      symmetryConnection: 'Pola mensir menunjukkan susunan yang sama di kiri dan kanan.',
      symmetryRelation: 'Pola mensir menunjukkan susunan yang sama di kiri dan kanan.',
    },
    {
      id: 'komik2-relief-lingkaran',
      title: 'Relief Lingkaran',
      description: 'Relief bundar yang terlihat pada ukiran Candi Penataran dan mudah dipelajari sebagai bangun datar.',
      page: 5,
      qrImage: qr18.src,
      qrTitle: 'Relief Lingkaran',
      qrDescription: 'Lihat bentuk bundar pada relief lingkaran.',
      navImage: navReliefLingkaran.src,
      objectImage: navReliefLingkaran.src,
      image: navReliefLingkaran.src,
      model3DUrl: 'https://asblr.com/cW7Lsm',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Relief lingkaran memberi kita contoh bangun datar yang bundar dan tidak punya sudut.',
      question: 'Bangun datar apa yang terlihat pada relief lingkaran?',
      answer: 'Relief lingkaran adalah lingkaran.',
      simpleExplanation: 'Relief lingkaran adalah lingkaran.',
      feedback: 'Benar, bentuk lingkaran mudah dikenali dari sisi yang melengkung.',
      shapeKey: 'lingkaran',
      shapeName: 'Lingkaran',
      shape: 'Lingkaran',
      symmetryConnection: 'Lingkaran bisa dibagi menjadi dua bagian yang sama dan seimbang.',
      symmetryRelation: 'Lingkaran bisa dibagi menjadi dua bagian yang sama dan seimbang.',
    },
    {
      id: 'komik2-ornamen-belah-ketupat',
      title: 'Ornamen Belah Ketupat',
      description: 'Ornamen yang menyerupai bentuk wajik pada ukiran Candi Penataran dan berkaitan dengan simetri.',
      page: 6,
      qrImage: qr17.src,
      qrTitle: 'Ornamen Belah Ketupat',
      qrDescription: 'Amati bentuk wajik pada ornamen belah ketupat.',
      navImage: navTangga.src,
      objectImage: navTangga.src,
      image: navTangga.src,
      model3DUrl: 'https://asblr.com/ljcPsy',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Ornamen belah ketupat punya sisi yang sama panjang dan bentuknya mirip wajik.',
      question: 'Bangun datar apa yang terlihat pada ornamen ini?',
      answer: 'Ornamen ini adalah belah ketupat.',
      simpleExplanation: 'Ornamen ini adalah belah ketupat.',
      feedback: 'Bagus, ornamen belah ketupat membantu kita mengenali bangun datar belah ketupat.',
      shapeKey: 'belah-ketupat',
      shapeName: 'Belah Ketupat',
      shape: 'Belah Ketupat',
      symmetryConnection: 'Bentuknya terlihat seimbang saat kita melihat sumbu simetrinya.',
      symmetryRelation: 'Bentuknya terlihat seimbang saat kita melihat sumbu simetrinya.',
    },
  ],
  qrCode: [
    { id: 'komik2-qr-1', imageSrc: qr15.src, alt: 'QR Umpang', label: 'Umpang', description: 'Lihat bentuk panjang dan seimbang pada Umpang.' },
    { id: 'komik2-qr-2', imageSrc: qr13.src, alt: 'QR Bale Agung', label: 'Bale Agung', description: 'Amati bidang panjang yang tampak pada Bale Agung.' },
    { id: 'komik2-qr-3', imageSrc: qr17.src, alt: 'QR Candi Angka', label: 'Candi Angka', description: 'Perhatikan bentuk runcing dan simetris pada Candi Angka.' },
    { id: 'komik2-qr-4', imageSrc: qr13.src, alt: 'QR Mensir', label: 'Mensir', description: 'Bandingkan pola persegi yang berulang pada Mensir.' },
    { id: 'komik2-qr-5', imageSrc: qr18.src, alt: 'QR Relief Lingkaran', label: 'Relief Lingkaran', description: 'Lihat bentuk bundar pada relief lingkaran.' },
    { id: 'komik2-qr-6', imageSrc: qr17.src, alt: 'QR Ornamen Belah Ketupat', label: 'Ornamen Belah Ketupat', description: 'Amati bentuk wajik pada ornamen belah ketupat.' },
  ],
  model3D: [
    { id: 'komik2-model-1', title: 'Umpang', arUrl: 'https://asblr.com/MmAMdg', page: 1, description: 'Lihat bentuk Umpang sebagai contoh persegi panjang.' },
    { id: 'komik2-model-2', title: 'Bale Agung', arUrl: 'https://asblr.com/yvcuaW', page: 2, description: 'Amati bidang panjang pada Bale Agung.' },
    { id: 'komik2-model-3', title: 'Candi Angka', arUrl: 'https://asblr.com/ljcPsy', page: 3, description: 'Perhatikan bentuk segitiga sama kaki pada Candi Angka.' },
    { id: 'komik2-model-4', title: 'Mensir', arUrl: 'https://asblr.com/yvcuaW', page: 4, description: 'Bandingkan pola persegi pada Mensir.' },
    { id: 'komik2-model-5', title: 'Relief Lingkaran', arUrl: 'https://asblr.com/cW7Lsm', page: 5, description: 'Amati bentuk lingkaran pada relief.' },
    { id: 'komik2-model-6', title: 'Ornamen Belah Ketupat', arUrl: 'https://asblr.com/ljcPsy', page: 6, description: 'Perhatikan bentuk belah ketupat pada ornamen.' },
  ],
  aiPrompt: {
    navigation: 'Gunakan bahasa sederhana untuk menjelaskan objek pada Candi Penataran dengan fokus pada bangun datar dan simetri.',
    objectTutor: 'Bantu siswa mengamati Umpang, Bale Agung, Candi Angka, Mensir, relief lingkaran, dan ornamen belah ketupat pada Candi Penataran.',
    application: 'Bantu siswa menghubungkan bentuk datar dengan situasi baru yang serupa.',
    argumentation: 'Beri umpan balik tentang alasan siswa memodelkan bentuk candi sebagai bangun datar.',
    resolution: 'Bimbing siswa menyelesaikan latihan pada bangun datar.',
    introspection: 'Buat refleksi singkat yang menekankan pemahaman pola dan simetri.',
  },
  identification: {
    questions: [
      {
        id: 'komik2-ident-1',
        question: 'Apa saja bentuk dasar yang kamu temukan saat membaca Comic Candi Penataran?',
        image: qr13.src,
        imageAlt: 'Motif relief persegi pada dinding Candi Penataran.',
        options: [
          { text: 'Persegi', correct: true },
          { text: 'Persegi Panjang', correct: true },
          { text: 'Segitiga Sama Sisi', correct: true },
          { text: 'Segitiga Sama Kaki', correct: true },
          { text: 'Lingkaran', correct: true },
          { text: 'Belah Ketupat', correct: true },
        ],
        explanation: 'Kamu bisa menandai semua bentuk yang muncul saat membaca Comic. Ini membantu mengingat kembali bagian-bagian candi yang kamu lihat.',
      },
      {
        id: 'komik2-ident-2',
        question: 'Bentuk bangun datar apa saja yang muncul pada bagian-bagian Candi Penataran yang kamu baca?',
        image: navUmpang.src,
        imageAlt: 'Bagian Umpang pada Candi Penataran yang tampak panjang dan seimbang.',
        options: [
          { text: 'Persegi', correct: true },
          { text: 'Persegi Panjang', correct: true },
          { text: 'Segitiga Sama Sisi', correct: true },
          { text: 'Segitiga Sama Kaki', correct: true },
          { text: 'Lingkaran', correct: true },
          { text: 'Belah Ketupat', correct: true },
        ],
        explanation: 'Yuk ingat kembali bagian-bagian candi yang sudah kamu lihat. Setiap bentuk yang muncul bisa kamu tandai sebagai bagian dari ingatanmu.',
      },
      {
        id: 'komik2-ident-3',
        question: 'Yuk tandai semua bentuk yang berhasil kamu temukan pada Comic Candi Penataran.',
        image: qr17.src,
        imageAlt: 'Bagian atap Candi Angka yang tampak runcing dan seimbang.',
        options: [
          { text: 'Persegi', correct: true },
          { text: 'Persegi Panjang', correct: true },
          { text: 'Segitiga Sama Sisi', correct: true },
          { text: 'Segitiga Sama Kaki', correct: true },
          { text: 'Lingkaran', correct: true },
          { text: 'Belah Ketupat', correct: true },
        ],
        explanation: 'Kamu sudah mengenali beberapa bentuk pada Candi Penataran. Coba cek kembali bagian Comic yang paling kamu ingat.',
      },
    ],
    feedback: {
      complete: 'Kamu sudah berhasil mengenali sebagian besar bentuk pada Candi Penataran.',
      partial: 'Cobaingat kembali bagian-bagian candi yang muncul pada Comic. Kamu masih bisa menambah ingatanmu.',
      incomplete: 'Yuk baca kembali bagian Comic dan cek bentuk-bentuk yang kamu lihat.',
    },
  },
  application: {
    title: 'Terapkan Ilmu di Konteks Baru',
    intro: 'Amati pola relief dan bentuk bangun datar pada candi, lalu pilih bangun datar yang paling cocok.',
    prompt: 'Relief Candi Penataran menampilkan pola yang simetris dan berulang. Pilih bangun datar yang paling cocok untuk menjelaskan pola tersebut dan jelaskan alasanmu.',
    context: 'Pola simetri dan bentuk bangun datar pada relief Candi Penataran.',
    images: [
      { src: navMensir.src, alt: 'Relief persegi', label: 'Relief Simetris', description: 'Amati pola berulang yang seimbang.' },
      { src: navUmpang.src, alt: 'Bidang panjang', label: 'Bidang Panjang', description: 'Perhatikan sisi panjang dan pendek.' },
      { src: navGapura.src, alt: 'Ornamen tajam', label: 'Ornamen Tajam', description: 'Lihat sudut dan sisi yang membentuk bangun tajam.' },
    ],
    options: [
      { value: 'Persegi', label: 'Persegi' },
      { value: 'Persegi Panjang', label: 'Persegi Panjang' },
      { value: 'Segitiga', label: 'Segitiga' },
      { value: 'Belah Ketupat', label: 'Belah Ketupat' },
    ],
  },
  argumentation: {
    questions: [
      {
        id: 'komik2-arg-1',
        templePart: 'relief persegi',
        question: 'Mengapa pola persegi pada relief Candi Penataran dapat dikatakan memiliki simetri yang kuat?',
        photoSrc: navMensir.src,
        photoAlt: 'Relief Candi Penataran tampak berulang dalam pola persegi',
        shapeName: 'Persegi',
        shapeKey: 'persegi',
        shapeSrc: '/images/navigation/persegi.svg',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik2-arg-2',
        templePart: 'bidang panjang',
        question: 'Mengapa bidang panjang pada arsitektur Candi Penataran cocok disebut persegi panjang?',
        photoSrc: navUmpang.src,
        photoAlt: 'Bidang panjang pada Candi Penataran',
        shapeName: 'Persegi Panjang',
        shapeKey: 'persegi-panjang',
        shapeSrc: '/images/navigation/persegi-panjang.svg',
        highlightColor: 'border-secondary-500',
      },
    ],
  },
  resolution: {
    missions: [
      {
        id: 1,
        title: 'Misi 1 · Luas Persegi',
        part: 'Relief Persegi',
        shape: 'Persegi',
        prompt: 'Sebuah persegi memiliki panjang sisi 8 cm. Berapakah luasnya?',
        options: [
          { key: 'A', label: '32 cm²' },
          { key: 'B', label: '48 cm²' },
          { key: 'C', label: '64 cm²' },
          { key: 'D', label: '72 cm²' },
        ],
        correctKey: 'C',
        answer: '64 cm²',
        formula: 'L = s × s = 8 × 8 = 64 cm²',
        explanation: 'Luas persegi dihitung dari sisi dikali sisi.',
        aiHint: 'Ingat rumus luas persegi: L = s².',
        context: 'Pola persegi pada relief Candi Penataran menunjukkan susunan yang sama di kiri dan kanan.',
        accent: 'from-primary-600 to-primary-700',
        illustration: '/images/navigation/persegi.svg',
      },
      {
        id: 2,
        title: 'Misi 2 · Luas Persegi Panjang',
        part: 'Bidang Panjang',
        shape: 'Persegi Panjang',
        prompt: 'Sebuah persegi panjang berukuran panjang 12 cm dan lebar 6 cm. Berapakah luasnya?',
        options: [
          { key: 'A', label: '54 cm²' },
          { key: 'B', label: '60 cm²' },
          { key: 'C', label: '66 cm²' },
          { key: 'D', label: '72 cm²' },
        ],
        correctKey: 'D',
        answer: '72 cm²',
        formula: 'L = p × l = 12 × 6 = 72 cm²',
        explanation: 'Luas persegi panjang dihitung dari panjang dikali lebar.',
        aiHint: 'Kalikan panjang dan lebar dengan hati-hati.',
        context: 'Bidang panjang pada Candi Penataran membantu kita melihat bentuk yang lebih lebar dari persegi.',
        accent: 'from-secondary-500 to-secondary-600',
        illustration: '/images/navigation/persegi-panjang.svg',
      },
    ],
  },
  introspection: {
    checklist: [
      'Saya memahami pola simetri pada Candi Penataran.',
      'Saya dapat mengenali persegi, persegi panjang, segitiga, dan belah ketupat.',
      'Saya lebih percaya diri menyelesaikan soal serupa tentang luas.',
    ],
    completionMessage: 'Kamu telah menyelesaikan pembelajaran pada Candi Penataran.',
    nextPrompt: 'Lanjutkar ke komik berikutnya untuk mempelajari konsep baru.',
  },
  report: {
    summary: 'Laporan ini menampilkan hasil pemahamanmu terhadap bangun datar pada candi.',
    learnedShapes: ['Persegi', 'Persegi Panjang', 'Segitiga', 'Belah Ketupat'],
  },
};
