import type { ComicContentPackageLike } from '../../types';
import coverImg from '@/features/comics/comic-2/assets/cover/cover.png';
import thumbnailImg from '@/features/comics/comic-2/assets/cover/thumbnail.png';
import navUmpang from '@/features/comics/comic-2/assets/navigation/umpang.png';
import navBalaiAgung from '@/features/comics/comic-2/assets/navigation/balaiagung.png';
import navCandiInduk from '@/features/comics/comic-2/assets/navigation/candiinduk.png';
import navPendopo from '@/features/comics/comic-2/assets/navigation/pendopo.png';
import navReliefCandi from '@/features/comics/comic-2/assets/navigation/reliefcandi.png';
import navAtapCandi from '@/features/comics/comic-2/assets/navigation/candiangka.png';
import qr13 from '@/features/comics/comic-2/assets/qr/13-objek-1.jpeg';
import qr15 from '@/features/comics/comic-2/assets/qr/15-objek-2.jpeg';
import qr17 from '@/features/comics/comic-2/assets/qr/17-objek-3.jpeg';
import qr18 from '@/features/comics/comic-2/assets/qr/18-objek-4.jpeg';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 2,
    title: 'Petualangan Simetri Candi Penataran',
    subtitle: 'Etnomatematika Bangun Datar',
    location: 'Candi Penataran, Blitar',
    classLevel: 'V',
    cover: coverImg.src,
    thumbnail: thumbnailImg.src,
    learningTargets: [
      'Mengamati objek yang muncul di Candi Penataran.',
      'Menghubungkan bangun datar dengan bentuk nyata pada candi.',
      'Menggunakan bahasa sederhana untuk menjelaskan simetri dan pola.',
    ],
    synopsis: 'Pembelajaran untuk bangun datar di Candi Penataran.',
  },
  learningObjects: [
    {
      id: 'komik2-umpang',
      title: 'Umpang',
      description: 'Umpang memperlihatkan bentuk persegi panjang yang rapi pada Candi Penataran. Bentuknya membantu kita melihat sisi yang seimbang dan simetris.',
      page: 1,
      qrImage: qr15.src,
      qrTitle: 'Umpang',
      qrDescription: 'Amati bentuk persegi panjang yang rapi pada Umpang.',
      navImage: navUmpang.src,
      objectImage: navUmpang.src,
      image: navUmpang.src,
      model3DUrl: 'https://asblr.com/MmAMdg',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Umpang tampak seperti persegi panjang. Perhatikan sisi panjang dan pendeknya serta kesamaan bentuk kiri dan kanan.',
      question: 'Bagaimana bentuk Umpang terlihat?',
      answer: 'Umpang terlihat seperti persegi panjang yang rapi dan seimbang.',
      simpleExplanation: 'Umpang terlihat seperti persegi panjang yang rapi dan seimbang.',
      feedback: 'Benar, Umpang dapat dipelajari sebagai contoh bangun datar persegi panjang.',
      shapeKey: 'persegi-panjang',
      shapeName: 'Persegi Panjang',
      shape: 'Persegi Panjang',
      symmetryConnection: 'Sisi kiri dan kanan Umpang membantu kita melihat keseimbangan bentuk pada Candi Penataran.',
      symmetryRelation: 'Sisi kiri dan kanan Umpang membantu kita melihat keseimbangan bentuk pada Candi Penataran.',
    },
    {
      id: 'komik2-bale-agung',
      title: 'Balai Agung',
      description: 'Balai Agung menampilkan bidang panjang yang mirip persegi panjang. Bentuknya membantu kita melihat keteraturan dan simetri pada bangunan candi.',
      page: 2,
      qrImage: qr13.src,
      qrTitle: 'Balai Agung',
      qrDescription: 'Amati bidang panjang yang rapi pada Balai Agung.',
      navImage: navBalaiAgung.src,
      objectImage: navBalaiAgung.src,
      image: navBalaiAgung.src,
      model3DUrl: 'https://asblr.com/yvcuaW',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Balai Agung tampak seperti persegi panjang. Perhatikan sisi-sisinya yang sejajar dan tampak seimbang.',
      question: 'Bangun datar apa yang paling terlihat pada Balai Agung?',
      answer: 'Balai Agung tampak seperti persegi panjang.',
      simpleExplanation: 'Balai Agung tampak seperti persegi panjang.',
      feedback: 'Bagus, Balai Agung dapat kita pelajari sebagai contoh persegi panjang.',
      shapeKey: 'persegi-panjang',
      shapeName: 'Persegi Panjang',
      shape: 'Persegi Panjang',
      symmetryConnection: 'Balai Agung membantu kita melihat bahwa bentuk yang seimbang sering muncul pada bangunan candi.',
      symmetryRelation: 'Balai Agung membantu kita melihat bahwa bentuk yang seimbang sering muncul pada bangunan candi.',
    },
    {
      id: 'komik2-candi-angka',
      title: 'Atap Candi (Candi Angka Tahun)',
      description: 'Atap Candi Angka Tahun membentuk segitiga yang rapi dan simetris. Kita bisa mengamati garis lurus yang sama di kedua sisi.',
      page: 3,
      qrImage: qr17.src,
      qrTitle: 'Atap Candi (Candi Angka Tahun)',
      qrDescription: 'Perhatikan bentuk segitiga yang simetris pada atap Candi Angka Tahun.',
      navImage: navAtapCandi.src,
      objectImage: navAtapCandi.src,
      image: navAtapCandi.src,
      model3DUrl: 'https://asblr.com/ljcPsy',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Atap Candi (Candi Angka Tahun) tampak seperti segitiga. Perhatikan sisi-sisinya yang sama panjang dan garis simetrinya.',
      question: 'Bangun datar apa yang terlihat pada atap candi ini?',
      answer: 'Atap candi ini tampak seperti segitiga.',
      simpleExplanation: 'Atap candi ini tampak seperti segitiga.',
      feedback: 'Benar, bentuknya bisa dipelajari sebagai segitiga.',
      shapeKey: 'segitiga',
      shapeName: 'Segitiga',
      shape: 'Segitiga',
      symmetryConnection: 'Garis simetri pada atap membantu kita melihat keseimbangan bentuknya.',
      symmetryRelation: 'Garis simetri pada atap membantu kita melihat keseimbangan bentuknya.',
    },
    {
      id: 'komik2-mensir',
      title: 'Candi Induk',
      description: 'Candi Induk menunjukkan bentuk persegi panjang yang tegak dan rapi. Kita bisa mengamati keteraturan garis dan simetri pada bagian utamanya.',
      page: 4,
      qrImage: qr13.src,
      qrTitle: 'Candi Induk',
      qrDescription: 'Amati bentuk persegi panjang yang tegak pada Candi Induk.',
      navImage: navCandiInduk.src,
      objectImage: navCandiInduk.src,
      image: navCandiInduk.src,
      model3DUrl: 'https://asblr.com/yvcuaW',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Candi Induk dapat diamati sebagai bagian yang menunjukkan bentuk persegi panjang yang teratur dan simetris.',
      question: 'Bangun datar apa yang terlihat pada Candi Induk?',
      answer: 'Candi Induk tampak seperti persegi panjang.',
      simpleExplanation: 'Candi Induk tampak seperti persegi panjang.',
      feedback: 'Bagus, Candi Induk membantu kita mengenali bangun datar persegi panjang.',
      shapeKey: 'persegi-panjang',
      shapeName: 'Persegi Panjang',
      shape: 'Persegi Panjang',
      symmetryConnection: 'Pola bagian utama Candi Induk menunjukkan susunan yang sama di kiri dan kanan.',
      symmetryRelation: 'Pola bagian utama Candi Induk menunjukkan susunan yang sama di kiri dan kanan.',
    },
    {
      id: 'komik2-relief-lingkaran',
      title: 'Pendopo Teras',
      description: 'Pendopo Teras memperlihatkan bidang persegi panjang yang tersusun dengan rapi. Bentuknya membantu kita mengamati keteraturan dan simetri pada bagian candi.',
      page: 5,
      qrImage: qr18.src,
      qrTitle: 'Pendopo Teras',
      qrDescription: 'Amati bentuk persegi panjang yang teratur pada Pendopo Teras.',
      navImage: navPendopo.src,
      objectImage: navPendopo.src,
      image: navPendopo.src,
      model3DUrl: 'https://asblr.com/cW7Lsm',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Pendopo Teras menunjukkan bentuk persegi panjang yang tersusun dengan rapi dan mudah dihubungkan dengan simetri.',
      question: 'Bangun datar apa yang terlihat pada Pendopo Teras?',
      answer: 'Pendopo Teras tampak seperti persegi panjang.',
      simpleExplanation: 'Pendopo Teras tampak seperti persegi panjang.',
      feedback: 'Benar, Pendopo Teras membantu kita mengenali bangun datar persegi panjang.',
      shapeKey: 'persegi-panjang',
      shapeName: 'Persegi Panjang',
      shape: 'Persegi Panjang',
      symmetryConnection: 'Bentuk Pendopo Teras memperlihatkan keseimbangan yang tampak jelas pada bagian candi.',
      symmetryRelation: 'Bentuk Pendopo Teras memperlihatkan keseimbangan yang tampak jelas pada bagian candi.',
    },
    {
      id: 'komik2-ornamen-belah-ketupat',
      title: 'Relief Candi',
      description: 'Relief Candi memperlihatkan pola berulang yang membantu kita mengenali bangun datar dan simetri pada ukiran candi.',
      page: 6,
      qrImage: qr17.src,
      qrTitle: 'Relief Candi',
      qrDescription: 'Amati pola berulang yang membantu memahami simetri pada Relief Candi.',
      navImage: navReliefCandi.src,
      objectImage: navReliefCandi.src,
      image: navReliefCandi.src,
      model3DUrl: 'https://asblr.com/ljcPsy',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Relief Candi menunjukkan susunan bentuk yang dapat dilihat sebagai persegi panjang yang berulang dan simetris.',
      question: 'Bangun datar apa yang terlihat pada relief ini?',
      answer: 'Relief ini tampak seperti persegi panjang.',
      simpleExplanation: 'Relief ini tampak seperti persegi panjang.',
      feedback: 'Bagus, Relief Candi membantu kita mengenali bangun datar persegi panjang.',
      shapeKey: 'persegi-panjang',
      shapeName: 'Persegi Panjang',
      shape: 'Persegi Panjang',
      symmetryConnection: 'Relief Candi menunjukkan pola yang seimbang saat dilihat dari sisi kiri dan kanan.',
      symmetryRelation: 'Relief Candi menunjukkan pola yang seimbang saat dilihat dari sisi kiri dan kanan.',
    },
  ],
  qrCode: [
    { id: 'komik2-umpang', imageSrc: qr15.src, alt: 'QR Umpang', label: 'Umpang', description: 'Amati bentuk persegi panjang yang rapi pada Umpang.' },
    { id: 'komik2-bale-agung', imageSrc: qr13.src, alt: 'QR Balai Agung', label: 'Balai Agung', description: 'Amati bidang panjang yang rapi pada Balai Agung.' },
    { id: 'komik2-candi-angka', imageSrc: qr17.src, alt: 'QR Atap Candi', label: 'Atap Candi (Candi Angka Tahun)', description: 'Perhatikan bentuk segitiga yang simetris pada atap candi.' },
    { id: 'komik2-mensir', imageSrc: qr13.src, alt: 'QR Candi Induk', label: 'Candi Induk', description: 'Amati bentuk persegi panjang yang tegak pada Candi Induk.' },
    { id: 'komik2-relief-lingkaran', imageSrc: qr18.src, alt: 'QR Pendopo Teras', label: 'Pendopo Teras', description: 'Amati bentuk persegi panjang yang teratur pada Pendopo Teras.' },
    { id: 'komik2-ornamen-belah-ketupat', imageSrc: qr17.src, alt: 'QR Relief Candi', label: 'Relief Candi', description: 'Amati pola berulang yang membantu memahami simetri pada Relief Candi.' },
  ],
  model3D: [
    { id: 'komik2-umpang', title: 'Umpang', arUrl: 'https://asblr.com/MmAMdg', page: 1, description: 'Lihat Umpang sebagai contoh persegi panjang yang seimbang.' },
    { id: 'komik2-bale-agung', title: 'Balai Agung', arUrl: 'https://asblr.com/yvcuaW', page: 2, description: 'Amati Balai Agung sebagai bidang persegi panjang yang rapi.' },
    { id: 'komik2-candi-angka', title: 'Atap Candi (Candi Angka Tahun)', arUrl: 'https://asblr.com/ljcPsy', page: 3, description: 'Perhatikan bentuk segitiga yang simetris pada atap candi.' },
    { id: 'komik2-mensir', title: 'Candi Induk', arUrl: 'https://asblr.com/yvcuaW', page: 4, description: 'Bandingkan bentuk persegi panjang pada bagian utama Candi Induk.' },
    { id: 'komik2-relief-lingkaran', title: 'Pendopo Teras', arUrl: 'https://asblr.com/cW7Lsm', page: 5, description: 'Amati bentuk persegi panjang yang teratur pada Pendopo Teras.' },
    { id: 'komik2-ornamen-belah-ketupat', title: 'Relief Candi', arUrl: 'https://asblr.com/ljcPsy', page: 6, description: 'Perhatikan pola berulang yang menegaskan simetri pada Relief Candi.' },
  ],
  aiPrompt: {
    navigation: 'Gunakan bahasa sederhana untuk menjelaskan objek pada Candi Penataran dengan fokus pada bangun datar dan simetri.',
    objectTutor: 'Bantu siswa mengamati Umpang, Balai Agung, Atap Candi (Candi Angka Tahun), Candi Induk, Pendopo Teras, dan Relief Candi pada Candi Penataran.',
    application: 'Bantu siswa menghubungkan bentuk datar dengan situasi baru yang serupa.',
    argumentation: 'Beri umpan balik tentang alasan siswa memodelkan bentuk candi sebagai bangun datar.',
    resolution: 'Bimbing siswa menyelesaikan latihan pada bangun datar.',
    introspection: 'Buat refleksi singkat yang menekankan pemahaman pola dan simetri.',
  },
  identification: {
    questions: [
      {
        id: 'komik2-ident-1',
        question: 'Apa saja bentuk dasar yang kamu temukan saat membaca Comic Candi Penataran?',
        image: qr13.src,
        imageAlt: 'Motif relief persegi panjang pada dinding Candi Penataran.',
        options: [
          { text: 'Persegi', correct: true },
          { text: 'Persegi Panjang', correct: true },
          { text: 'Segitiga', correct: true },
          { text: 'Lingkaran', correct: true },
          { text: 'Belah Ketupat', correct: true },
        ],
        explanation: 'Kamu bisa menandai semua bentuk yang muncul saat membaca Comic. Ini membantu mengingat kembali bagian-bagian candi yang kamu lihat.',
      },
      {
        id: 'komik2-ident-2',
        question: 'Bentuk bangun datar apa saja yang muncul pada bagian-bagian Candi Penataran yang kamu baca?',
        image: navUmpang.src,
        imageAlt: 'Bagian Umpang pada Candi Penataran yang tampak panjang dan seimbang.',
        options: [
          { text: 'Persegi', correct: true },
          { text: 'Persegi Panjang', correct: true },
          { text: 'Segitiga', correct: true },
          { text: 'Lingkaran', correct: true },
          { text: 'Belah Ketupat', correct: true },
        ],
        explanation: 'Yuk ingat kembali bagian-bagian candi yang sudah kamu lihat. Setiap bentuk yang muncul bisa kamu tandai sebagai bagian dari ingatanmu.',
      },
      {
        id: 'komik2-ident-3',
        question: 'Yuk tandai semua bentuk yang berhasil kamu temukan pada Comic Candi Penataran.',
        image: navAtapCandi.src,
        imageAlt: 'Bagian atap Candi Angka Tahun yang tampak segitiga dan seimbang.',
        options: [
          { text: 'Persegi', correct: true },
          { text: 'Persegi Panjang', correct: true },
          { text: 'Segitiga', correct: true },
          { text: 'Lingkaran', correct: true },
          { text: 'Belah Ketupat', correct: true },
        ],
        explanation: 'Kamu sudah mengenali beberapa bentuk pada Candi Penataran. Coba cek kembali bagian Comic yang paling kamu ingat.',
      },
    ],
    feedback: {
      complete: 'Kamu sudah berhasil mengenali sebagian besar bentuk pada Candi Penataran.',
      partial: 'Coba ingat kembali bagian-bagian candi yang muncul pada Comic. Kamu masih bisa menambah ingatanmu.',
      incomplete: 'Yuk baca kembali bagian Comic dan cek bentuk-bentuk yang kamu lihat.',
    },
  },
  application: {
    title: 'Terapkan Ilmu di Konteks Baru',
    intro: 'Amati pola relief dan bentuk bangun datar pada candi, lalu pilih bangun datar yang paling cocok.',
    prompt: 'Relief Candi Penataran menampilkan pola yang simetris dan berulang. Pilih bangun datar yang paling cocok untuk menjelaskan pola tersebut dan jelaskan alasanmu.',
    context: 'Pola simetri dan bentuk bangun datar pada relief Candi Penataran.',
    images: [
      { src: navReliefCandi.src, alt: 'Relief Candi', label: 'Relief Candi', description: 'Amati pola berulang yang seimbang pada relief candi.' },
      { src: navUmpang.src, alt: 'Umpang', label: 'Umpang', description: 'Perhatikan sisi panjang dan pendek pada Umpang.' },
      { src: navAtapCandi.src, alt: 'Atap Candi', label: 'Atap Candi', description: 'Lihat bentuk segitiga yang simetris pada atap candi.' },
    ],
    options: [
      { value: 'Persegi', label: 'Persegi' },
      { value: 'Persegi Panjang', label: 'Persegi Panjang' },
      { value: 'Segitiga', label: 'Segitiga' },
      { value: 'Belah Ketupat', label: 'Belah Ketupat' },
    ],
  },
  argumentation: {
    questions: [
      {
        id: 'komik2-arg-1',
        templePart: 'relief candi',
        question: 'Mengapa pola pada Relief Candi dapat dikatakan memiliki simetri yang kuat?',
        photoSrc: navReliefCandi.src,
        photoAlt: 'Relief Candi Penataran tampak berulang dalam pola simetris',
        shapeName: 'Persegi Panjang',
        shapeKey: 'persegi-panjang',
        shapeSrc: '/images/navigation/persegi-panjang.svg',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik2-arg-2',
        templePart: 'atap candi',
        question: 'Mengapa atap candi pada Candi Penataran cocok disebut segitiga?',
        photoSrc: navAtapCandi.src,
        photoAlt: 'Atap Candi Penataran tampak seperti segitiga',
        shapeName: 'Segitiga',
        shapeKey: 'segitiga',
        shapeSrc: '/images/navigation/segitiga.svg',
        highlightColor: 'border-secondary-500',
      },
    ],
  },
  resolution: {
    missions: [
      {
        id: 1,
        title: 'Misi 1 · Luas Persegi',
        part: 'Relief Persegi',
        shape: 'Persegi',
        prompt: 'Sebuah persegi memiliki panjang sisi 8 cm. Berapakah luasnya?',
        options: [
          { key: 'A', label: '32 cm²' },
          { key: 'B', label: '48 cm²' },
          { key: 'C', label: '64 cm²' },
          { key: 'D', label: '72 cm²' },
        ],
        correctKey: 'C',
        answer: '64 cm²',
        formula: 'L = s × s = 8 × 8 = 64 cm²',
        explanation: 'Luas persegi dihitung dari sisi dikali sisi.',
        aiHint: 'Ingat rumus luas persegi: L = s².',
        context: 'Pola persegi pada relief Candi Penataran menunjukkan susunan yang sama di kiri dan kanan.',
        accent: 'from-primary-600 to-primary-700',
        illustration: '/images/navigation/persegi.svg',
      },
      {
        id: 2,
        title: 'Misi 2 · Luas Persegi Panjang',
        part: 'Bidang Panjang',
        shape: 'Persegi Panjang',
        prompt: 'Sebuah persegi panjang berukuran panjang 12 cm dan lebar 6 cm. Berapakah luasnya?',
        options: [
          { key: 'A', label: '54 cm²' },
          { key: 'B', label: '60 cm²' },
          { key: 'C', label: '66 cm²' },
          { key: 'D', label: '72 cm²' },
        ],
        correctKey: 'D',
        answer: '72 cm²',
        formula: 'L = p × l = 12 × 6 = 72 cm²',
        explanation: 'Luas persegi panjang dihitung dari panjang dikali lebar.',
        aiHint: 'Kalikan panjang dan lebar dengan hati-hati.',
        context: 'Bidang panjang pada Candi Penataran membantu kita melihat bentuk yang lebih lebar dari persegi.',
        accent: 'from-secondary-500 to-secondary-600',
        illustration: '/images/navigation/persegi-panjang.svg',
      },
    ],
  },
  introspection: {
    checklist: [
      'Saya memahami pola simetri pada Candi Penataran.',
      'Saya dapat mengenali persegi, persegi panjang, segitiga, dan belah ketupat.',
      'Saya lebih percaya diri menyelesaikan soal serupa tentang luas.',
    ],
    completionMessage: 'Kamu telah menyelesaikan pembelajaran pada Candi Penataran.',
    nextPrompt: 'Lanjutkan ke komik berikutnya untuk mempelajari konsep baru.',
  },
  report: {
    summary: 'Laporan ini menampilkan hasil pemahamanmu terhadap bangun datar pada candi.',
    learnedShapes: ['Persegi', 'Persegi Panjang', 'Segitiga', 'Belah Ketupat'],
  },
};
