import type { ComicContentPackageLike } from '../../types';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 2,
    title: 'Petualangan Simetri Candi Penataran',
    subtitle: 'Etnomatematika Bangun Datar',
    location: 'Candi Penataran, Blitar',
    classLevel: 'V',
    cover: '/assets/images/komik-2/cover.png',
    thumbnail: '/assets/images/komik-2/thumbnail.png',
    learningTargets: [
      'Mengamati objek yang muncul di Candi Penataran.',
      'Menghubungkan bangun datar dengan bentuk nyata pada candi.',
      'Menggunakan bahasa sederhana untuk menjelaskan simetri dan pola.',
    ],
    synopsis: 'Pembelajaran untuk bangun datar di Candi Penataran.',
  },
  learningObjects: [
    {
      id: 'komik2-umpang',
      title: 'Umpang',
      description: 'Bagian rumah adat yang terlihat panjang dan seimbang pada Candi Penataran.',
      page: 1,
      qrImage: '/assets/qr/komik-2/15-objek-2.jpeg',
      navImage: '/assets/images/komik-2/umpang.png',
      objectImage: '/assets/images/komik-2/umpang.png',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Bentuk permukaan Umpang menyerupai persegi panjang. Amati sisi panjang dan pendeknya dengan hati-hati.',
      question: 'Bagaimana bentuk Umpang terlihat?',
      answer: 'Umpang terlihat seperti persegi panjang yang panjang dan seimbang.',
      feedback: 'Benar, Umpang dapat dipelajari sebagai contoh bangun datar persegi panjang.',
      shapeKey: 'persegi-panjang',
      shapeName: 'Persegi Panjang',
      symmetryConnection: 'Sisi kiri dan kanan Umpang membantu kita melihat keseimbangan bentuk pada candi.',
    },
    {
      id: 'komik2-bale-agung',
      title: 'Bale Agung',
      description: 'Bagian bangunan yang tampak luas dan rapi pada Candi Penataran.',
      page: 2,
      qrImage: '/assets/qr/komik-2/13-objek-1.jpeg',
      navImage: '/assets/images/komik-2/bale-agung.png',
      objectImage: '/assets/images/komik-2/bale-agung.png',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Bale Agung punya bidang yang tampak panjang dan membentuk persegi panjang. Perhatikan sisi-sisinya.',
      question: 'Apa bangun datar yang paling terlihat pada Bale Agung?',
      answer: 'Bale Agung tampak seperti persegi panjang.',
      feedback: 'Bagus, bale agung dapat kita pelajari sebagai contoh persegi panjang.',
      shapeKey: 'persegi-panjang',
      shapeName: 'Persegi Panjang',
      symmetryConnection: 'Bale Agung membantu kita melihat bahwa bentuk yang seimbang sering muncul pada bangunan.',
    },
    {
      id: 'komik2-candi-angka',
      title: 'Candi Angka',
      description: 'Bagian candi yang menampilkan bentuk runcing dan simetris pada Candi Penataran.',
      page: 3,
      qrImage: '/assets/qr/komik-2/17-objek-3.jpeg',
      navImage: '/assets/images/komik-2/gapura.png',
      objectImage: '/assets/images/komik-2/gapura.png',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Candi Angka memiliki bentuk yang mirip segitiga sama kaki. Perhatikan sisi-sisi yang sama panjang.',
      question: 'Bangun datar apa yang terlihat pada Candi Angka?',
      answer: 'Candi Angka tampak seperti segitiga sama kaki.',
      feedback: 'Benar, bentuknya bisa dipelajari sebagai segitiga sama kaki.',
      shapeKey: 'segitiga-sama-kaki',
      shapeName: 'Segitiga Sama Kaki',
      symmetryConnection: 'Bentuknya terlihat seimbang ketika dibagi menjadi dua bagian yang sama.',
    },
    {
      id: 'komik2-mensir',
      title: 'Mensir',
      description: 'Bagian ornamen yang tampak seperti persegi dan berhubungan dengan simetri pada Candi Penataran.',
      page: 4,
      qrImage: '/assets/qr/komik-2/13-objek-1.jpeg',
      navImage: '/assets/images/komik-2/mensir.png',
      objectImage: '/assets/images/komik-2/mensir.png',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Mensir bisa diamati sebagai pola persegi yang berulang dan rapi pada candi.',
      question: 'Apa bangun datar yang terlihat pada Mensir?',
      answer: 'Mensir terlihat seperti persegi.',
      feedback: 'Bagus, mensir membantu kita mengenali bangun datar persegi.',
      shapeKey: 'persegi',
      shapeName: 'Persegi',
      symmetryConnection: 'Pola mensir menunjukkan susunan yang sama di kiri dan kanan.',
    },
    {
      id: 'komik2-relief-lingkaran',
      title: 'Relief Lingkaran',
      description: 'Relief bundar yang terlihat pada ukiran Candi Penataran dan mudah dipelajari sebagai bangun datar.',
      page: 5,
      qrImage: '/assets/qr/komik-2/18-objek-4.jpeg',
      navImage: '/assets/images/komik-2/relief-lingkaran.png',
      objectImage: '/assets/images/komik-2/relief-lingkaran.png',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Relief lingkaran memberi kita contoh bangun datar yang bundar dan tidak punya sudut.',
      question: 'Bangun datar apa yang terlihat pada relief lingkaran?',
      answer: 'Relief lingkaran adalah lingkaran.',
      feedback: 'Benar, bentuk lingkaran mudah dikenali dari sisi yang melengkung.',
      shapeKey: 'lingkaran',
      shapeName: 'Lingkaran',
      symmetryConnection: 'Lingkaran bisa dibagi menjadi dua bagian yang sama dan seimbang.',
    },
    {
      id: 'komik2-ornamen-belah-ketupat',
      title: 'Ornamen Belah Ketupat',
      description: 'Ornamen yang menyerupai bentuk wajik pada ukiran Candi Penataran dan berkaitan dengan simetri.',
      page: 6,
      qrImage: '/assets/qr/komik-2/17-objek-3.jpeg',
      navImage: '/assets/images/komik-2/tangga.png',
      objectImage: '/assets/images/komik-2/tangga.png',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Ornamen belah ketupat punya sisi yang sama panjang dan bentuknya mirip wajik.',
      question: 'Bangun datar apa yang terlihat pada ornamen ini?',
      answer: 'Ornamen ini adalah belah ketupat.',
      feedback: 'Bagus, ornamen belah ketupat membantu kita mengenali bangun datar belah ketupat.',
      shapeKey: 'belah-ketupat',
      shapeName: 'Belah Ketupat',
      symmetryConnection: 'Bentuknya terlihat seimbang saat kita melihat sumbu simetrinya.',
    },
  ],
  qrCode: [
    { id: 'komik2-qr-1', imageSrc: '/assets/qr/komik-2/15-objek-2.jpeg', alt: 'QR Umpang', label: 'Umpang', description: 'Lihat bentuk panjang dan seimbang pada Umpang.' },
    { id: 'komik2-qr-2', imageSrc: '/assets/qr/komik-2/13-objek-1.jpeg', alt: 'QR Bale Agung', label: 'Bale Agung', description: 'Amati bidang panjang yang tampak pada Bale Agung.' },
    { id: 'komik2-qr-3', imageSrc: '/assets/qr/komik-2/17-objek-3.jpeg', alt: 'QR Candi Angka', label: 'Candi Angka', description: 'Perhatikan bentuk runcing dan simetris pada Candi Angka.' },
    { id: 'komik2-qr-4', imageSrc: '/assets/qr/komik-2/13-objek-1.jpeg', alt: 'QR Mensir', label: 'Mensir', description: 'Bandingkan pola persegi yang berulang pada Mensir.' },
    { id: 'komik2-qr-5', imageSrc: '/assets/qr/komik-2/18-objek-4.jpeg', alt: 'QR Relief Lingkaran', label: 'Relief Lingkaran', description: 'Lihat bentuk bundar pada relief lingkaran.' },
    { id: 'komik2-qr-6', imageSrc: '/assets/qr/komik-2/17-objek-3.jpeg', alt: 'QR Ornamen Belah Ketupat', label: 'Ornamen Belah Ketupat', description: 'Amati bentuk wajik pada ornamen belah ketupat.' },
  ],
  model3D: [
    { id: 'komik2-model-1', title: 'Umpang', arUrl: '', page: 1, description: 'Lihat bentuk Umpang sebagai contoh persegi panjang.' },
    { id: 'komik2-model-2', title: 'Bale Agung', arUrl: '', page: 2, description: 'Amati bidang panjang pada Bale Agung.' },
    { id: 'komik2-model-3', title: 'Candi Angka', arUrl: '', page: 3, description: 'Perhatikan bentuk segitiga sama kaki pada Candi Angka.' },
    { id: 'komik2-model-4', title: 'Mensir', arUrl: '', page: 4, description: 'Bandingkan pola persegi pada Mensir.' },
    { id: 'komik2-model-5', title: 'Relief Lingkaran', arUrl: '', page: 5, description: 'Amati bentuk lingkaran pada relief.' },
    { id: 'komik2-model-6', title: 'Ornamen Belah Ketupat', arUrl: '', page: 6, description: 'Perhatikan bentuk belah ketupat pada ornamen.' },
  ],
  aiPrompt: {
    navigation: 'Gunakan bahasa sederhana untuk menjelaskan objek pada Candi Penataran dengan fokus pada bangun datar dan simetri.',
    objectTutor: 'Bantu siswa mengamati Umpang, Bale Agung, Candi Angka, Mensir, relief lingkaran, dan ornamen belah ketupat pada Candi Penataran.',
    application: 'Bantu siswa menghubungkan bentuk datar dengan situasi baru yang serupa.',
    argumentation: 'Beri umpan balik tentang alasan siswa memodelkan bentuk candi sebagai bangun datar.',
    resolution: 'Bimbing siswa menyelesaikan latihan pada bangun datar.',
    introspection: 'Buat refleksi singkat yang menekankan pemahaman pola dan simetri.',
  },
  identification: {
    questions: [
      {
        id: 'komik2-ident-1',
        question: 'Perhatikan motif relief persegi pada dinding Candi Penataran. Bangun datar apa yang paling sesuai dengan bentuk motif ini?',
        image: '/assets/qr/komik-2/13-objek-1.jpeg',
        imageAlt: 'Motif relief persegi pada dinding Candi Penataran.',
        options: [
          { text: 'Persegi', correct: true },
          { text: 'Persegi Panjang', correct: false },
          { text: 'Segitiga Sama Sisi', correct: false },
          { text: 'Segitiga Sama Kaki', correct: false },
          { text: 'Lingkaran', correct: false },
          { text: 'Belah Ketupat', correct: false },
        ],
        explanation: 'Motif relief ini berbentuk persegi. Persegi punya empat sisi sama panjang dan empat sudut siku-siku.',
      },
      {
        id: 'komik2-ident-2',
        question: 'Perhatikan batu candi yang tampak panjang pada bagian sisi bangunan. Bangun datar apa yang paling sesuai dengan bentuknya?',
        image: '/assets/images/komik-2/umpang.png',
        imageAlt: 'Batu candi berbentuk persegi panjang pada Candi Penataran.',
        options: [
          { text: 'Persegi', correct: false },
          { text: 'Persegi Panjang', correct: true },
          { text: 'Segitiga Sama Sisi', correct: false },
          { text: 'Segitiga Sama Kaki', correct: false },
          { text: 'Lingkaran', correct: false },
          { text: 'Belah Ketupat', correct: false },
        ],
        explanation: 'Bentuk batu candi ini adalah persegi panjang. Ia memiliki dua pasang sisi yang sama panjang dan sudut-sudutnya siku-siku.',
      },
      {
        id: 'komik2-ident-3',
        question: 'Perhatikan hiasan atap candi yang terlihat runcing dan sama di semua sisinya. Bangun datar apa yang paling sesuai?',
        image: '/assets/qr/komik-2/17-objek-3.jpeg',
        imageAlt: 'Hiasan atap candi berbentuk segitiga sama sisi.',
        options: [
          { text: 'Persegi', correct: false },
          { text: 'Persegi Panjang', correct: false },
          { text: 'Segitiga Sama Sisi', correct: true },
          { text: 'Segitiga Sama Kaki', correct: false },
          { text: 'Lingkaran', correct: false },
          { text: 'Belah Ketupat', correct: false },
        ],
        explanation: 'Hiasan ini membentuk segitiga sama sisi. Ketiga sisinya sama panjang dan bentuknya seimbang.',
      },
      {
        id: 'komik2-ident-4',
        question: 'Perhatikan ornamen candi yang mirip segitiga dengan dua sisi sama panjang. Bangun datar apa yang paling sesuai?',
        image: '/assets/qr/komik-2/17-objek-3.jpeg',
        imageAlt: 'Ornamen candi berbentuk segitiga sama kaki.',
        options: [
          { text: 'Persegi', correct: false },
          { text: 'Persegi Panjang', correct: false },
          { text: 'Segitiga Sama Sisi', correct: false },
          { text: 'Segitiga Sama Kaki', correct: true },
          { text: 'Lingkaran', correct: false },
          { text: 'Belah Ketupat', correct: false },
        ],
        explanation: 'Ornamen ini adalah segitiga sama kaki. Bentuknya punya dua sisi sama panjang dan satu garis simetri.',
      },
      {
        id: 'komik2-ident-5',
        question: 'Perhatikan relief lingkaran pada ukiran Candi Penataran. Bangun datar apa yang paling sesuai dengan bentuk ini?',
        image: '/assets/qr/komik-2/13-objek-1.jpeg',
        imageAlt: 'Relief lingkaran pada ukiran Candi Penataran.',
        options: [
          { text: 'Persegi', correct: false },
          { text: 'Persegi Panjang', correct: false },
          { text: 'Segitiga Sama Sisi', correct: false },
          { text: 'Segitiga Sama Kaki', correct: false },
          { text: 'Lingkaran', correct: true },
          { text: 'Belah Ketupat', correct: false },
        ],
        explanation: 'Bentuk ini adalah lingkaran. Lingkaran bundar dan tidak punya sudut.',
      },
      {
        id: 'komik2-ident-6',
        question: 'Perhatikan hiasan berbentuk belah ketupat pada ukiran Candi Penataran. Bangun datar apa yang paling sesuai?',
        image: '/assets/images/komik-2/relief-lingkaran.png',
        imageAlt: 'Hiasan berbentuk belah ketupat pada Candi Penataran.',
        options: [
          { text: 'Persegi', correct: false },
          { text: 'Persegi Panjang', correct: false },
          { text: 'Segitiga Sama Sisi', correct: false },
          { text: 'Segitiga Sama Kaki', correct: false },
          { text: 'Lingkaran', correct: false },
          { text: 'Belah Ketupat', correct: true },
        ],
        explanation: 'Hiasan ini berbentuk belah ketupat. Bentuk ini punya empat sisi sama panjang dan terlihat seperti wajik.',
      },
    ],
    feedback: {
      complete: 'Hebat! Kamu berhasil mengenali bentuk dan simetri yang muncul pada Candi Penataran.',
      partial: 'Coba perhatikan lagi bagian kiri dan kanan bangunan. Apakah bentuknya sama dan seimbang?',
      incomplete: 'Perhatikan objek pada komik lagi, terutama bagian yang menunjukkan garis simetri dan bentuk yang sama di kedua sisi.',
    },
  },
  application: {
    title: 'Terapkan Ilmu di Konteks Baru',
    intro: 'Amati pola relief dan bentuk bangun datar pada candi, lalu pilih bangun datar yang paling cocok.',
    prompt: 'Relief Candi Penataran menampilkan pola yang simetris dan berulang. Pilih bangun datar yang paling cocok untuk menjelaskan pola tersebut dan jelaskan alasanmu.',
    context: 'Pola simetri dan bentuk bangun datar pada relief Candi Penataran.',
    images: [
      { src: '/assets/images/komik-2/mensir.png', alt: 'Relief persegi', label: 'Relief Simetris', description: 'Amati pola berulang yang seimbang.' },
      { src: '/assets/images/komik-2/umpang.png', alt: 'Bidang panjang', label: 'Bidang Panjang', description: 'Perhatikan sisi panjang dan pendek.' },
      { src: '/assets/images/komik-2/gapura.png', alt: 'Ornamen tajam', label: 'Ornamen Tajam', description: 'Lihat sudut dan sisi yang membentuk bangun tajam.' },
    ],
    options: [
      { value: 'Persegi', label: 'Persegi' },
      { value: 'Persegi Panjang', label: 'Persegi Panjang' },
      { value: 'Segitiga', label: 'Segitiga' },
      { value: 'Belah Ketupat', label: 'Belah Ketupat' },
    ],
  },
  argumentation: {
    questions: [
      {
        id: 'komik2-arg-1',
        templePart: 'relief persegi',
        question: 'Mengapa pola persegi pada relief Candi Penataran dapat dikatakan memiliki simetri yang kuat?',
        photoSrc: '/assets/images/komik-2/mensir.png',
        photoAlt: 'Relief Candi Penataran tampak berulang dalam pola persegi',
        shapeName: 'Persegi',
        shapeKey: 'persegi',
        shapeSrc: '/images/navigation/persegi.svg',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik2-arg-2',
        templePart: 'bidang panjang',
        question: 'Mengapa bidang panjang pada arsitektur Candi Penataran cocok disebut persegi panjang?',
        photoSrc: '/assets/images/komik-2/umpang.png',
        photoAlt: 'Bidang panjang pada Candi Penataran',
        shapeName: 'Persegi Panjang',
        shapeKey: 'persegi-panjang',
        shapeSrc: '/images/navigation/persegi-panjang.svg',
        highlightColor: 'border-secondary-500',
      },
    ],
  },
  resolution: {
    missions: [
      {
        id: 1,
        title: 'Misi 1 · Luas Persegi',
        part: 'Relief Persegi',
        shape: 'Persegi',
        prompt: 'Sebuah persegi memiliki panjang sisi 8 cm. Berapakah luasnya?',
        options: [
          { key: 'A', label: '32 cm²' },
          { key: 'B', label: '48 cm²' },
          { key: 'C', label: '64 cm²' },
          { key: 'D', label: '72 cm²' },
        ],
        correctKey: 'C',
        answer: '64 cm²',
        formula: 'L = s × s = 8 × 8 = 64 cm²',
        explanation: 'Luas persegi dihitung dari sisi dikali sisi.',
        aiHint: 'Ingat rumus luas persegi: L = s².',
        context: 'Pola persegi pada relief Candi Penataran menunjukkan susunan yang sama di kiri dan kanan.',
        accent: 'from-primary-600 to-primary-700',
        illustration: '/images/navigation/persegi.svg',
      },
      {
        id: 2,
        title: 'Misi 2 · Luas Persegi Panjang',
        part: 'Bidang Panjang',
        shape: 'Persegi Panjang',
        prompt: 'Sebuah persegi panjang berukuran panjang 12 cm dan lebar 6 cm. Berapakah luasnya?',
        options: [
          { key: 'A', label: '54 cm²' },
          { key: 'B', label: '60 cm²' },
          { key: 'C', label: '66 cm²' },
          { key: 'D', label: '72 cm²' },
        ],
        correctKey: 'D',
        answer: '72 cm²',
        formula: 'L = p × l = 12 × 6 = 72 cm²',
        explanation: 'Luas persegi panjang dihitung dari panjang dikali lebar.',
        aiHint: 'Kalikan panjang dan lebar dengan hati-hati.',
        context: 'Bidang panjang pada Candi Penataran membantu kita melihat bentuk yang lebih lebar dari persegi.',
        accent: 'from-secondary-500 to-secondary-600',
        illustration: '/images/navigation/persegi-panjang.svg',
      },
    ],
  },
  introspection: {
    checklist: [
      'Saya memahami pola simetri pada Candi Penataran.',
      'Saya dapat mengenali persegi, persegi panjang, segitiga, dan belah ketupat.',
      'Saya lebih percaya diri menyelesaikan soal serupa tentang luas.',
    ],
    completionMessage: 'Kamu telah menyelesaikan pembelajaran pada Candi Penataran.',
    nextPrompt: 'Lanjutkar ke komik berikutnya untuk mempelajari konsep baru.',
  },
  report: {
    summary: 'Laporan ini menampilkan hasil pemahamanmu terhadap bangun datar pada candi.',
    learnedShapes: ['Persegi', 'Persegi Panjang', 'Segitiga', 'Belah Ketupat'],
  },
};
