import type { ComicContentPackageLike } from '../../types';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 3,
    title: 'Petualangan di Rumah Gajah Mungkur',
    subtitle: 'Etnomatematika Bangun Datar',
    location: 'Rumah Gajah Mungkur, Gresik',
    classLevel: 'II',
    cover: '/comics/komik-3/cover.png',
    thumbnail: '/comics/komik-3/thumbnail.png',
    learningTargets: [
      'Mengenali bangun datar sederhana di sekitar rumah dan bangunan bersejarah.',
      'Membandingkan bentuk persegi, segitiga, lingkaran, dan jajargenjang.',
      'Menyusun dan mengurai bentuk bangun datar.',
    ],
    synopsis: 'Pembelajaran untuk bangun datar di Rumah Gajah Mungkur.',
  },
  learningObjects: [
    {
      id: 'komik3-persegi',
      title: 'Persegi',
      description: 'Bentuk persegi pada bagian halaman bangunan.',
      page: 1,
      qrImage: '/images/navigation/default.svg',
      objectImage: '/images/navigation/default.svg',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Jelaskan ciri persegi yang terlihat pada bangunan ini.',
      question: 'Apa ciri persegi?',
      answer: 'Persegi memiliki empat sisi sama panjang dan empat sudut siku-siku.',
      feedback: 'Benar, persegi aman dikenali karena semua sisinya sama.',
    },
    {
      id: 'komik3-segitiga',
      title: 'Segitiga',
      description: 'Bentuk atap rumah yang tajam.',
      page: 2,
      qrImage: '/images/navigation/default.svg',
      objectImage: '/images/navigation/default.svg',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Jelaskan mengapa atap dapat dipahami sebagai segitiga.',
      question: 'Mengapa atap bisa dikatakan segitiga?',
      answer: 'Karena atap memiliki tiga sisi dan tiga sudut.',
      feedback: 'Benar, segitiga memiliki tiga sisi dan tiga sudut.',
    },
  ],
  qrCode: [
    { id: 'komik3-qr-1', imageSrc: '/images/navigation/default.svg', alt: 'QR Persegi', label: 'Persegi', description: 'Scan untuk melihat bentuk persegi.' },
    { id: 'komik3-qr-2', imageSrc: '/images/navigation/default.svg', alt: 'QR Segitiga', label: 'Segitiga', description: 'Scan untuk melihat bentuk segitiga.' },
  ],
  model3D: [
    { id: 'komik3-model-1', title: 'Persegi', arUrl: '', page: 1, description: 'Model 3D persegi untuk pengamatan sederhana.' },
    { id: 'komik3-model-2', title: 'Segitiga', arUrl: '', page: 2, description: 'Model 3D segitiga untuk pengamatan sudut.' },
  ],
  aiPrompt: {
    navigation: 'Bantu siswa mengenali bangun datar sederhana dengan bahasa yang mudah dipahami.',
    objectTutor: 'Jelaskan bangun datar dengan contoh yang dekat dengan kehidupan siswa.',
    application: 'Bantu siswa menghubungkan bangun datar dengan benda nyata di sekitar.',
    argumentation: 'Beri umpan balik sederhana tentang alasan siswa.',
    resolution: 'Bimbing siswa menyelesaikan latihan bangun datar sederhana.',
    introspection: 'Buat refleksi singkat dengan bahasa yang sederhana dan positif.',
  },
  identification: {
    questions: [
      {
        id: 'komik2-ident-6',
        question: 'Amati bangunan runtuh pendopo yang tampak seperti berlian. Bangun datar apakah yang paling sesuai?',
        image: '/images/navigation/default.svg',
        imageAlt: 'Bangunan runtuh pendopo pada Candi Penataran yang tampak seperti berlian.',
        options: [
          { text: 'Belah Ketupat', correct: true },
          { text: 'Lingkaran', correct: false },
          { text: 'Persegi', correct: false },
          { text: 'Sisi Kanan', correct: false },
        ],
        explanation: 'Bangunan runtuh pendopo pada komik menggambarkan belah ketupat, bentuk yang memiliki dua garis simetri.',
      },
      {
        id: 'komik3-ident-2',
        question: 'Bagian atap rumah ini paling cocok disebut bangun datar apa?',
        image: '/images/navigation/default.svg',
        imageAlt: 'Atap rumah terlihat berbentuk segitiga.',
        options: [
          { text: 'Segitiga', correct: true },
          { text: 'Persegi', correct: false },
          { text: 'Bujur Sangkar', correct: false },
          { text: 'Lingkaran', correct: false },
        ],
        explanation: 'Atap rumah dapat dilihat sebagai segitiga karena memiliki tiga sisi.',
      },
    ],
    feedback: {
      complete: 'Sangat bagus! Kamu mengenali bangun datar dengan baik.',
      partial: 'Masih ada beberapa bentuk yang perlu diperiksa ulang.',
      incomplete: 'Lihat kembali bentuk-bentuk yang ada pada bangunan.',
    },
  },
  application: {
    title: 'Terapkan Ilmu di Konteks Baru',
    intro: 'Temukan bangun datar yang ada di sekitar benda',
    prompt: 'Pilih bangun datar yang paling cocok dengan benda yang kamu amati.',
    context: 'Benda-benda yang ada di sekitar rumah dan bangunan bersejarah.',
    images: [
      { src: '/images/navigation/default.svg', alt: 'Bentuk persegi', label: 'Persegi', description: 'Perhatikan sisi dan sudutnya.' },
      { src: '/images/navigation/default.svg', alt: 'Bentuk segitiga', label: 'Segitiga', description: 'Perhatikan sisi dan sudutnya.' },
    ],
    options: [
      { value: 'Persegi', label: 'Persegi' },
      { value: 'Segitiga', label: 'Segitiga' },
      { value: 'Lingkaran', label: 'Lingkaran' },
    ],
  },
  argumentation: {
    questions: [
      {
        id: 'komik3-arg-1',
        templePart: 'bagian depan rumah',
        question: 'Mengapa bentuk bagian depan rumah bisa dipahami sebagai persegi?',
        photoSrc: '/images/navigation/default.svg',
        photoAlt: 'Bagian depan rumah',
        shapeName: 'Persegi',
        shapeKey: 'persegi',
        shapeSrc: '/images/navigation/default.svg',
        highlightColor: 'border-primary-500',
      },
    ],
  },
  resolution: {
    missions: [
      {
        id: 1,
        title: 'Misi 1 · Luas Persegi',
        part: 'Bagian Depan',
        shape: 'Persegi',
        prompt: 'Sebuah persegi memiliki panjang sisi 4 cm. Berapakah luasnya?',
        options: [
          { key: 'A', label: '8 cm²' },
          { key: 'B', label: '12 cm²' },
          { key: 'C', label: '16 cm²' },
          { key: 'D', label: '20 cm²' },
        ],
        correctKey: 'C',
        answer: '16 cm²',
        formula: 'L = s × s = 4 × 4 = 16 cm²',
        explanation: 'Luas persegi dihitung dari sisi dikali sisi.',
        aiHint: 'Ingat rumus luas persegi.',
        context: 'Bentuk yang kamu lihat pada bangunan rumah.',
        accent: 'from-primary-600 to-primary-700',
        illustration: '/images/navigation/default.svg',
      },
    ],
  },
  introspection: {
    checklist: [
      'Saya dapat mengenali bentuk bangun datar sederhana.',
      'Saya tahu perbedaan persegi dan segitiga.',
      'Saya lebih percaya diri mengamati benda di sekitar.',
    ],
    completionMessage: 'Kamu telah menyelesaikan pembelajaran pada komik ini.',
    nextPrompt: 'Kamu bisa mengulang lagi bila ingin lebih percaya diri.',
  },
  report: {
    summary: 'Laporan ini menampilkan hasil pemahamanmu terhadap bangun datar sederhana.',
    learnedShapes: ['Persegi', 'Segitiga'],
  },
};
